begin;
do $$
declare uid uuid:=gen_random_uuid(); test_email text:=gen_random_uuid()||'@example.invalid'; sid text:=gen_random_uuid()::text; eid text:=gen_random_uuid()::text; cid text:=gen_random_uuid()::text; pid text:=gen_random_uuid()::text; pid2 text:=gen_random_uuid()::text; o jsonb;f jsonb;candidate jsonb;p jsonb;p2 jsonb;doc jsonb;updated jsonb;v bigint;total numeric;
begin
 if has_function_privilege('anon','public.centro_payment_document(text)','execute') or has_function_privilege('authenticated','public.centro_record_payment_document(jsonb,jsonb,jsonb)','execute') or has_table_privilege('authenticated','public.centro_payment_documents','select') then raise exception 'Private payment access exposed';end if;
 insert into auth.users(id,email,email_confirmed_at) values(uid,test_email,now());
 insert into public.centro_access values(test_email,'Teste transacional','Financeiro',null,true);
 perform set_config('request.jwt.claim.sub',uid::text,true);
 select data into o from public.centro_state where section='office' for update;
 o:=jsonb_set(o,'{students}',o->'students'||jsonb_build_array(jsonb_build_object('id',sid,'name','Aluno teste','documentNumber',sid)));
 o:=jsonb_set(o,'{courses}',o->'courses'||jsonb_build_array(jsonb_build_object('id',cid,'name','Curso teste','active',true)));
 o:=jsonb_set(o,'{entries}',o->'entries'||jsonb_build_array(jsonb_build_object('id',eid,'studentId',sid,'courseId',cid,'status','Confirmada','reference','MAT-TEST','history','[]'::jsonb)));
 update public.centro_state set data=o where section='office';
 select data,version into f,v from public.centro_state where section='finance' for update;
 f:=jsonb_set(f,'{charges}',f->'charges'||jsonb_build_array(jsonb_build_object('id',cid,'entryId',eid,'kind','Inscrição','month','','amount',10000,'due',current_date)));
 p:=jsonb_build_object('id',pid,'chargeId',cid,'amount',4000,'date',current_date,'method','Numerário','reference',pid,'actor','forged','voidReason','');
 f:=jsonb_set(f,'{payments}',f->'payments'||jsonb_build_array(p));
 v:=public.centro_save('finance',v,f);
 select data into f from public.centro_state where section='finance';
 if (select value->>'actor' from jsonb_array_elements(f->'payments') where value->>'id'=pid)<>'Financeiro' then raise exception 'Actor not assigned by server';end if;
 doc:=public.centro_payment_document(pid);
 if (doc->>'amount')::numeric<>4000 or doc->>'reference' not like 'PAG-%' then raise exception 'Payment receipt missing';end if;
 if public.centro_verify(doc->>'token') ?| array['name','amount','movementReference','method','voidReason'] then raise exception 'Public financial information exposed';end if;
 p2:=jsonb_build_object('id',pid2,'chargeId',cid,'amount',6000,'date',current_date,'method','Numerário','reference',pid,'actor','','voidReason','');
 candidate:=jsonb_set(f,'{payments}',f->'payments'||jsonb_build_array(p2));
 begin perform public.centro_save('finance',v,candidate);raise exception 'Duplicate reference accepted';exception when raise_exception then if sqlerrm='Duplicate reference accepted' then raise;end if;end;
 p2:=p2||jsonb_build_object('reference',pid2,'amount',6001);
 candidate:=jsonb_set(f,'{payments}',f->'payments'||jsonb_build_array(p2));
 begin perform public.centro_save('finance',v,candidate);raise exception 'Overpayment accepted';exception when raise_exception then if sqlerrm='Overpayment accepted' then raise;end if;end;
 p2:=p2||jsonb_build_object('amount',6000.5);
 candidate:=jsonb_set(f,'{payments}',f->'payments'||jsonb_build_array(p2));
 begin perform public.centro_save('finance',v,candidate);raise exception 'Fractional cents accepted';exception when raise_exception then if sqlerrm='Fractional cents accepted' then raise;end if;end;
 p2:=p2||jsonb_build_object('amount',6000);
 v:=public.centro_save('finance',v,jsonb_set(f,'{payments}',f->'payments'||jsonb_build_array(p2)));
 select data into f from public.centro_state where section='finance';
 v:=public.centro_save('finance',v,f);
 if public.centro_payment_document(pid)<>doc or (select count(*) from public.centro_payment_documents where payment_id in (pid,pid2))<>2 then raise exception 'Receipt changed or duplicated';end if;
 candidate:=jsonb_set(f,'{charges}',(select jsonb_agg(case when value->>'id'=cid then jsonb_set(value,'{amount}','20000') else value end) from jsonb_array_elements(f->'charges')));
 begin perform public.centro_save('finance',v,candidate);raise exception 'Original charge modified';exception when raise_exception then if sqlerrm='Original charge modified' then raise;end if;end;
 candidate:=jsonb_set(f,'{payments}',(select jsonb_agg(case when value->>'id'=pid then jsonb_set(value,'{voidReason}','"erro"') else value end) from jsonb_array_elements(f->'payments')));
 begin perform public.centro_save('finance',v,candidate);raise exception 'Short void reason accepted';exception when raise_exception then if sqlerrm='Short void reason accepted' then raise;end if;end;
 candidate:=jsonb_set(f,'{payments}',(select jsonb_agg(case when value->>'id'=pid then value||jsonb_build_object('voidReason','Correção do lançamento','voidActor','forged','voidAt','2000-01-01') else value end) from jsonb_array_elements(f->'payments')));
 v:=public.centro_save('finance',v,candidate);
 select data into f from public.centro_state where section='finance';
 updated:=public.centro_payment_document(pid);
 if updated-'voidReason'-'voidAt'<>doc-'voidReason'-'voidAt' or updated->>'voidReason'='' then raise exception 'Void lost original receipt';end if;
 if public.centro_verify(doc->>'token')->>'status'<>'Estornado' then raise exception 'Voided QR still active';end if;
 select sum((value->>'amount')::numeric) into total from jsonb_array_elements(f->'payments') where value->>'chargeId'=cid and value->>'voidReason'='';
 if total<>6000 then raise exception 'Void did not restore balance';end if;
 if (select value->>'voidActor' from jsonb_array_elements(f->'payments') where value->>'id'=pid)<>'Financeiro' then raise exception 'Void actor forged';end if;
 candidate:=jsonb_set(f,'{payments}',(select jsonb_agg(case when value->>'id'=pid then jsonb_set(value,'{amount}','1') else value end) from jsonb_array_elements(f->'payments')));
 begin perform public.centro_save('finance',v,candidate);raise exception 'Original payment modified';exception when raise_exception then if sqlerrm='Original payment modified' then raise;end if;end;
 update public.centro_access set role='Secretaria' where email=test_email;
 begin perform public.centro_payment_document(pid);raise exception 'Secretary financial access';exception when raise_exception then if sqlerrm='Secretary financial access' then raise;end if;end;
 update public.centro_access set role='Aluno' where email=test_email;
 begin perform public.centro_save('finance',v,f);raise exception 'Student finance write';exception when raise_exception then if sqlerrm='Student finance write' then raise;end if;end;
end $$;
rollback;
select 'PASS: partial payments, exact cents, duplicates, overpayment, immutable charges/receipts, void reason, server actor, QR status, balance and permissions' as result;
