begin;
do $$
declare uid uuid:=gen_random_uuid(); eid text:='test-'||gen_random_uuid(); sid text:='test-'||gen_random_uuid(); test_email text:=gen_random_uuid()||'@example.invalid'; cid text:='test-'||gen_random_uuid(); o jsonb; a jsonb; e jsonb; check_result jsonb; cert jsonb; d jsonb; i integer;
begin
 if has_function_privilege('anon','public.centro_certificate_list()','execute') or has_table_privilege('authenticated','public.centro_certificates','insert') then raise exception 'Certificate permissions exposed';end if;
 insert into auth.users(id,email,email_confirmed_at) values(uid,test_email,now());
 insert into public.centro_access values(test_email,'Teste transacional','Administrador',null,true);
 perform set_config('request.jwt.claim.sub',uid::text,true);
 select data into o from public.centro_state where section='office' for update;
 select data into a from public.centro_state where section='academic' for update;
 e:=jsonb_build_object('id',eid,'studentId',sid,'courseId',cid,'status','Confirmada','reference','MAT-TEST','history','[]'::jsonb,'period','Manhã','startDate',current_date-30);
 o:=jsonb_set(o,'{students}',o->'students'||jsonb_build_array(jsonb_build_object('id',sid,'name','Aluno de teste','documentNumber',sid)));
 o:=jsonb_set(o,'{courses}',o->'courses'||jsonb_build_array(jsonb_build_object('id',cid,'name','Curso de teste','active',true,'hours','40','duration','1 mês')));
 o:=jsonb_set(o,'{entries}',o->'entries'||jsonb_build_array(e));
 update public.centro_state set data=o where section='office';
 a:=jsonb_set(a,'{cohorts}',a->'cohorts'||jsonb_build_array(jsonb_build_object('id',cid,'name','Turma teste','courseId',cid,'start',current_date-30,'end',current_date-1)));
 a:=jsonb_set(a,'{assignments}',a->'assignments'||jsonb_build_object(eid,cid));
 for i in 1..4 loop a:=jsonb_set(a,'{sessions}',a->'sessions'||jsonb_build_array(jsonb_build_object('id',cid||i,'cohortId',cid,'date',current_date-i,'marks',jsonb_build_object(eid,case when i=4 then 'Falta' else 'Presente' end))));end loop;
 a:=jsonb_set(a,'{assessments}',a->'assessments'||jsonb_build_array(jsonb_build_object('id',cid,'cohortId',cid,'date',current_date-1,'scores',jsonb_build_object(eid,10))));
 update public.centro_state set data=a where section='academic';
 update public.centro_certificate_policy set confirmed_at=null,confirmed_by=null where id;
 begin perform public.centro_certificate_issue(eid,true);raise exception 'Unconfirmed policy allowed';exception when raise_exception then if sqlerrm='Unconfirmed policy allowed' then raise;end if;end;
 perform public.centro_certificate_policy_save(80,10,true);
 begin perform public.centro_certificate_issue(eid,true);raise exception 'Low attendance allowed';exception when raise_exception then if sqlerrm='Low attendance allowed' then raise;end if;end;
 perform public.centro_certificate_policy_save(75,11,true);
 begin perform public.centro_certificate_issue(eid,true);raise exception 'Low grade allowed';exception when raise_exception then if sqlerrm='Low grade allowed' then raise;end if;end;
 perform public.centro_certificate_policy_save(75,10,true);
 check_result:=public.centro_certificate_check(eid);
 if check_result->'reasons'<>'[]'::jsonb or (check_result->>'frequency')::numeric<>75 then raise exception 'Boundary eligibility failed';end if;
 update public.centro_state set data=jsonb_set(a,'{sessions}',(select jsonb_agg(case when value->>'id'=cid||1 then jsonb_set(value,'{marks}','{}') else value end) from jsonb_array_elements(a->'sessions'))) where section='academic';
 if jsonb_array_length(public.centro_certificate_check(eid)->'reasons')=0 then raise exception 'Missing attendance allowed';end if;
 update public.centro_state set data=jsonb_set(a,'{assessments}',(select jsonb_agg(case when value->>'id'=cid then jsonb_set(value,'{scores}','{}') else value end) from jsonb_array_elements(a->'assessments'))) where section='academic';
 if jsonb_array_length(public.centro_certificate_check(eid)->'reasons')=0 then raise exception 'Missing grade allowed';end if;
 update public.centro_state set data=jsonb_set(a,'{cohorts}',(select jsonb_agg(case when value->>'id'=cid then jsonb_set(value,'{end}',to_jsonb(current_date+1)) else value end) from jsonb_array_elements(a->'cohorts'))) where section='academic';
 if jsonb_array_length(public.centro_certificate_check(eid)->'reasons')=0 then raise exception 'Future completion allowed';end if;
 update public.centro_state set data=a where section='academic';
 update public.centro_access set role='Secretaria' where email=test_email;
 begin perform public.centro_certificate_policy_save(0,0,true);raise exception 'Secretary changed policy';exception when raise_exception then if sqlerrm='Secretary changed policy' then raise;end if;end;
 begin perform public.centro_certificate_issue(eid,false);raise exception 'No completion confirmation';exception when raise_exception then if sqlerrm='No completion confirmation' then raise;end if;end;
 cert:=public.centro_certificate_issue(eid,true);
 if cert->>'reference' not like 'CERT-%' or cert->>'status'<>'Concluído' then raise exception 'Certificate not issued';end if;
 if public.centro_certificate_issue(eid,true)<>cert or (select count(*) from public.centro_certificates where entry_id=eid)<>1 then raise exception 'Retry duplicated certificate';end if;
 update public.centro_state set data=jsonb_set(a,'{assessments}',(select jsonb_agg(case when value->>'id'=cid then jsonb_set(value,'{scores}',jsonb_build_object(eid,20)) else value end) from jsonb_array_elements(a->'assessments'))) where section='academic';
 if public.centro_certificate_issue(eid,true)<>cert then raise exception 'Snapshot changed';end if;
 d:=public.centro_verify(cert->>'token');
 if d->>'kind'<>'Certificado' or d ?| array['name','average','frequency','studentId','issued_by'] then raise exception 'Public verification privacy failed';end if;
 update public.centro_access set role='Aluno',person_id=sid where email=test_email;
 if jsonb_array_length(public.centro_certificate_list()->'certificates')<>1 then raise exception 'Own certificate missing';end if;
 update public.centro_access set person_id='unlinked' where email=test_email;
 if public.centro_certificate_list()->'certificates'<>'[]'::jsonb then raise exception 'Other student certificate exposed';end if;
 begin perform public.centro_certificate_issue(eid,true);raise exception 'Student issued certificate';exception when raise_exception then if sqlerrm='Student issued certificate' then raise;end if;end;
 update public.centro_access set role='Secretaria',active=false where email=test_email;
 begin perform public.centro_certificate_list();raise exception 'Suspended read';exception when raise_exception then if sqlerrm='Suspended read' then raise;end if;end;
end $$;
rollback;
select 'PASS: policy approval, roles, attendance, grades, missing records, end date, confirmation, idempotency, frozen snapshot, student isolation and QR privacy' as result;
