import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
async function model(path,replace=false){let js=ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;if(replace)js=js.replace("'./registration'",JSON.stringify(new URL('../lib/registration.ts',import.meta.url).href));return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));}
const {initialOffice}=await model('../lib/office.ts',true);
const {initialAcademic,cohortErrors,assignEntry,saveSession,saveAssessment,progress}=await model('../lib/academic.ts');
const today='2026-09-10';
test('seeded classes have valid schedules',()=>{const a=initialAcademic();for(const c of a.cohorts)assert.deepEqual(cohortErrors(c,a,initialOffice()),{});});
test('trainer and room collisions are rejected; adjacent slots allowed',()=>{const a=initialAcademic(),o=initialOffice();const c={...a.cohorts[0],id:'new',name:'Turma nova'};assert.ok(cohortErrors(c,a,o).from);assert.deepEqual(cohortErrors({...c,from:'11:00',to:'13:00'},a,o),{});});
test('only confirmed matching entries may be assigned, once',()=>{const a=initialAcademic(),o=initialOffice();assert.throws(()=>assignEntry(a,o,o.entries[0].id,'t1'));assert.throws(()=>assignEntry(a,o,o.entries[1].id,'t1'));assert.throws(()=>assignEntry(a,o,o.entries[3].id,'t1'));const clean={...a,assignments:{}};assert.equal(assignEntry(clean,o,o.entries[3].id,'t1').assignments[o.entries[3].id],'t1');});
test('session validates all students, ownership and school dates',()=>{const a=initialAcademic(),o=initialOffice(),s={cohortId:'t1',date:'2026-09-10',marks:{'PRE-DEMO-004':'Presente'}};assert.throws(()=>saveSession(a,o,s,'f2',today));assert.throws(()=>saveSession(a,o,{...s,marks:{}},'f1',today));assert.throws(()=>saveSession(a,o,{...s,date:'2026-09-09'},'f1',today));assert.throws(()=>saveSession(a,o,{...s,date:'2026-09-14'},'f1',today));});
test('editing a session replaces it instead of doubling attendance',()=>{let a=initialAcademic();const o=initialOffice();a=saveSession(a,o,{cohortId:'t1',date:'2026-09-08',marks:{'PRE-DEMO-004':'Falta'}},'f1',today);assert.equal(a.sessions.filter(s=>s.cohortId==='t1').length,1);assert.equal(progress(a,o.entries[3]).percent,0);});
test('grades accept zero and reject out-of-range, NaN, outsiders',()=>{const a=initialAcademic(),o=initialOffice(),base={id:'new',cohortId:'t1',name:'Teste prático',date:'2026-09-10'};for(const score of [-1,21,NaN])assert.throws(()=>saveAssessment(a,o,{...base,scores:{'PRE-DEMO-004':score}},'f1',today));assert.throws(()=>saveAssessment(a,o,{...base,scores:{unknown:10}},'f1',today));assert.throws(()=>saveAssessment(a,o,{...base,scores:{}},'f1',today));const r=saveAssessment(a,o,{...base,scores:{'PRE-DEMO-004':0}},'f1',today);assert.equal(progress(r,o.entries[3]).average,8);});
test('assessment edit and student portal share the updated result',()=>{const a=initialAcademic(),o=initialOffice();const r=saveAssessment(a,o,{...a.assessments[0],scores:{'PRE-DEMO-004':18}},'f1',today);assert.equal(r.assessments.length,1);assert.equal(progress(r,o.entries[3]).average,18);assert.equal(progress(r,o.entries[1]).average,null);});
