import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
async function source(path,replacements={}){let js=ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;for(const [key,value] of Object.entries(replacements))js=js.replaceAll("'"+key+"'",JSON.stringify(value));return 'data:text/javascript;base64,'+Buffer.from(js).toString('base64');}
const registration=new URL('../lib/registration.ts',import.meta.url).href;
const office=await source('../lib/office.ts',{'./registration':registration});
const {initialOffice,decideEntry}=await import(office);
const {createOfficeEnrolment,enrolmentErrors}=await import(await source('../lib/office-enrolment.ts',{'./office':office,'./registration':registration,'./academic':await source('../lib/academic.ts')}));
const date='2026-09-10T12:00:00Z';
function draft(o){return {student:{...o.students[0],id:'new-student',name:'Aluno Exemplo',documentNumber:'EXEMPLO123'},existing:false,courseId:o.courses[0].id,period:'Manhã',startDate:'2026-10-01',files:{photo:new File(['photo'],'foto.png'),identity:new File(['id'],'bi.pdf'),payment:new File(['proof'],'pagamento.pdf')}};}
test('both office roles create a pending enrolment, student and attached files',()=>{for(const role of ['Administrador','Secretaria']){const o=initialOffice(),d=draft(o),r=createOfficeEnrolment(o,d,role,'new-entry',date);assert.equal(r.students.length,o.students.length+1);const e=r.entries.at(-1);assert.equal(e.status,'Pendente');assert.equal(e.reference,'');assert.equal(e.attachments.identity,d.files.identity);assert.equal(e.history[0].actor,role);assert.equal(decideEntry(r,e.id,'Confirmada','',role,date).entries.at(-1).status,'Confirmada');}});
test('existing student enrols in another course without duplicate or overwritten personal data',()=>{const o=initialOffice(),d={...draft(o),student:{...o.students[0],name:'Must not overwrite'},existing:true,courseId:o.courses[2].id};const r=createOfficeEnrolment(o,d,'Secretaria','new-entry',date);assert.equal(r.students.length,o.students.length);assert.equal(r.students[0].name,o.students[0].name);assert.equal(r.entries.at(-1).studentId,o.students[0].id);});
test('duplicate identity, pending enrolment, inactive course and missing documents are blocked',()=>{const o=initialOffice();assert.ok(enrolmentErrors(o,{...draft(o),student:{...draft(o).student,documentNumber:o.students[0].documentNumber}},'2026-09-10').documentNumber);assert.ok(enrolmentErrors(o,{...draft(o),student:o.students[0],existing:true},'2026-09-10').duplicate);o.courses[0].active=false;const e=enrolmentErrors(o,{...draft(o),files:{photo:null,identity:null,payment:null}},'2026-09-10');for(const k of ['course','photo','identity','payment'])assert.ok(e[k]);});
test('other roles and repeated submission cannot create an enrolment',()=>{const o=initialOffice(),d=draft(o);for(const role of ['Aluno','Formador','Financeiro'])assert.throws(()=>createOfficeEnrolment(o,d,role,'new-entry',date));const r=createOfficeEnrolment(o,d,'Administrador','new-entry',date);assert.throws(()=>createOfficeEnrolment(r,d,'Administrador','new-entry',date));});
