import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
async function sourceURL(path,replacements={}){let js=ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;for(const [key,value] of Object.entries(replacements))js=js.replaceAll("'"+key+"'",JSON.stringify(value));return 'data:text/javascript;base64,'+Buffer.from(js).toString('base64');}
const academicURL=await sourceURL('../lib/academic.ts');
const {initialAcademic}=await import(academicURL);
const {initialOffice}=await import(await sourceURL('../lib/office.ts',{'./registration':new URL('../lib/registration.ts',import.meta.url).href}));
const {initialFinance,cents,addCharge,addPayment,balance,voidPayment,eligibility,issueCertificate,toCSV}=await import(await sourceURL('../lib/finance.ts',{'./academic':academicURL}));
const today='2026-09-10';
test('money uses exact cents and rejects ambiguous or negative inputs',()=>{assert.equal(cents('0,10'),10);assert.equal(cents('25000.55'),2500055);for(const n of ['0','-1','1.001','1e3','abc',''])assert.throws(()=>cents(n));});
test('monthly charges cannot repeat and require confirmed enrolment',()=>{const f=initialFinance(),o=initialOffice(),c={id:'new',entryId:'PRE-DEMO-004',kind:'Propina',month:'2026-09',amount:10000,due:today};assert.throws(()=>addCharge(f,o,c,'Financeiro'));assert.throws(()=>addCharge(f,o,{...c,entryId:'PRE-DEMO-001'},'Financeiro'));assert.equal(addCharge(f,o,{...c,month:'2026-10'},'Financeiro').charges.length,4);});
test('partial payments update balance and cannot overpay',()=>{const f=initialFinance(),p={id:'p',chargeId:'COB-DEMO-002',amount:500000,date:today,method:'Numerário',reference:'teste-003',actor:'',voidReason:''};const r=addPayment(f,p,'Financeiro',today);assert.equal(balance(r,r.charges[1]),1000000);assert.throws(()=>addPayment(f,{...p,amount:2000000},'Financeiro',today));assert.throws(()=>addPayment(r,{...p,id:'p2'},'Financeiro',today));});
test('estorno preserves the record and restores the balance',()=>{const f=initialFinance();assert.throws(()=>voidPayment(f,'PAG-DEMO-002','','Financeiro'));const r=voidPayment(f,'PAG-DEMO-002','Valor registado por engano','Financeiro');assert.equal(r.payments.length,f.payments.length);assert.equal(balance(r,r.charges[1]),2500000);assert.throws(()=>voidPayment(r,'PAG-DEMO-002','Outro motivo','Financeiro'));});
test('future payments and nonfinancial roles are rejected',()=>{const f=initialFinance(),p={id:'p',chargeId:'COB-DEMO-002',amount:100,date:'2027-01-01',method:'Numerário',reference:'teste',actor:'',voidReason:''};assert.throws(()=>addPayment(f,p,'Financeiro',today));assert.throws(()=>addPayment(f,{...p,date:today},'Secretaria',today));});
test('certificate requires course data, results and manual completion',()=>{const f=initialFinance(),o=initialOffice(),a=initialAcademic();assert.ok(eligibility(f,o,a,'PRE-DEMO-004').reasons.length);o.courses.find(c=>c.id==='c1-1').hours='40';o.courses.find(c=>c.id==='c1-1').duration='2 meses';assert.equal(eligibility(f,o,a,'PRE-DEMO-004').reasons.length,0);assert.throws(()=>issueCertificate(f,o,a,'PRE-DEMO-004',false,'Secretaria',today));const r=issueCertificate(f,o,a,'PRE-DEMO-004',true,'Secretaria',today);assert.equal(r.certificates[0].average,16);a.assessments[0].scores['PRE-DEMO-004']=2;assert.equal(r.certificates[0].average,16);assert.throws(()=>issueCertificate(r,o,a,'PRE-DEMO-004',true,'Secretaria',today));});
test('CSV neutralizes spreadsheet formulas and escapes quotes',()=>{const text=toCSV([['=CMD()', 'A "B"', '+123']]);assert.ok(text.includes("'=CMD()"));assert.ok(text.includes('A ""B""'));assert.ok(text.includes("'+123"));});
