"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {rpc} from '@/lib/supabase';
import type {Verification} from '@/lib/enrolment-document';
export default function Verify(){
 const [ref,setRef]=useState(''),[result,setResult]=useState<Verification|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const request=useRef(0);
 async function verify(value:string){const id=++request.current;setResult(null);setMessage('');const token=value.trim();if(!/^[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}$/i.test(token)){setBusy(false);setMessage('Introduza o código de verificação do comprovativo ou abra o respetivo QR code.');return;}setBusy(true);try{const data=await rpc<Verification|null>('centro_verify',{p_token:token});if(id!==request.current)return;setResult(data);if(!data)setMessage('Não foi encontrado um comprovativo confirmado para este código. Contacte a Secretaria.');}catch{if(id===request.current)setMessage('Não foi possível consultar o centro. Verifique a ligação e tente novamente.');}finally{if(id===request.current)setBusy(false);}}
 useEffect(()=>{const value=new URLSearchParams(location.search).get('ref')||'';setRef(value);if(value)void verify(value);return()=>{request.current++;};},[]);
 return <main style={{maxWidth:660,margin:'auto',padding:'48px 24px'}}><a href="/" style={{color:'#e96515',fontWeight:800}}>BEZA INOVAÇÕES</a><h1 style={{fontSize:30,margin:'28px 0 12px'}}>Verificar documento</h1><p>Confirme se a inscrição ou o certificado está registado no centro. O código encontra-se no PDF, junto ao QR.</p><form onSubmit={e=>{e.preventDefault();void verify(ref);}} style={{display:'grid',gap:12,margin:'24px 0'}}><label htmlFor="verification-code">Código de verificação</label><Input id="verification-code" value={ref} maxLength={36} onChange={e=>{request.current++;setRef(e.target.value);setResult(null);setMessage('');setBusy(false);}} autoComplete="off"/><Button type="submit" className="primary" disabled={busy}>{busy?'A verificar…':'Verificar documento'}</Button></form>{message&&<p role="status">{message}</p>}{result&&<section style={{padding:24,border:'1px solid #c7dfce',borderRadius:12}} aria-live="polite"><h2>{result.kind==='Certificado'?'Certificado de conclusão registado':'Inscrição confirmada'}</h2><dl>{[[result.kind==='Certificado'?'Certificado':'Matrícula',result.reference],['Curso',result.course],[result.kind==='Certificado'?'Carga horária':'Período',result.kind==='Certificado'?result.hours+' horas':result.period||'—'],['Emissão',new Date(result.issued).toLocaleDateString('pt-PT')]].map(([label,value])=><div key={label} style={{marginBottom:16}}><dt style={{fontWeight:700}}>{label}</dt><dd style={{margin:0}}>{value}</dd></div>)}</dl><p>Compare estes dados com o documento apresentado. {result.kind==='Certificado'?'Esta consulta confirma que o centro registou a conclusão da formação e emitiu este certificado.':'Esta consulta confirma o registo da inscrição e não certifica a conclusão do curso.'} Não substitui a assinatura e o carimbo.</p></section>}<p style={{marginTop:24}}>Esta consulta não mostra nomes, números de identificação, telefones ou anexos pessoais.</p><p>Secretaria: 947 968 650 / 952 042 462</p></main>;
}
