'use client';
import {useEffect,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import type {Session} from '@supabase/supabase-js';
import {supabase,rpc,sendRegistration} from '@/lib/supabase';
import {trainers,type Academic} from '@/lib/academic';
import type {Office} from '@/lib/office';
import type {Finance} from '@/lib/finance';
import {Button} from '@/components/ui/button';
export type Backend={role:string;personId:string;name:string;office:Office;academic:Academic;finance:Finance;versions:Record<string,number>;trainers:{id:string;name:string}[]};
export function useBackend(){const [session,setSession]=useState<Session|null>(null),[data,setData]=useState<Backend|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const locked=useRef(false);const pending=useRef<(()=>Promise<void>)|null>(null);
 async function refresh(){const result=await rpc<Backend>('centro_load');trainers.splice(0,trainers.length,...result.trainers);setData(result);}
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data:{session}})=>{if(live){setSession(session);setLoading(false);}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(previous=>{if(previous?.user.id!==s?.user.id)setData(null);return s;});setError('');});return()=>{live=false;subscription.unsubscribe();};},[]);
 useEffect(()=>{if(!session)return;setLoading(true);refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[session?.user.id]);
 async function run(task:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');pending.current=task;try{await task();pending.current=null;}catch(e){setError((e as Error).message);}finally{locked.current=false;setBusy(false);}}
 function setter<K extends 'office'|'academic'|'finance'>(section:K):Dispatch<SetStateAction<Backend[K]>>{return value=>{if(!data||locked.current)return;const next=typeof value==='function'?(value as (v:Backend[K])=>Backend[K])(data[section]):value;void run(async()=>{if(section==='office'){const office=next as Office;const fresh=office.entries.filter(e=>!data.office.entries.some(old=>old.id===e.id));if(fresh.length){if(fresh.length!==1)throw new Error('Registe uma inscrição de cada vez.');const e=fresh[0];const student=office.students.find(s=>s.id===e.studentId)!;const course=office.courses.find(c=>c.id===e.courseId);await sendRegistration({...student,course:course?.name||'Outro',otherCourse:e.requestedCourse||'',period:e.period,startDate:e.startDate},e.attachments||{},e.id.match(/[0-9a-f]{8}-[0-9a-f-]{27}/i)?.[0]||crypto.randomUUID());await refresh();return;}}await rpc('centro_save',{p_section:section,p_version:data.versions[section],p_data:next});await refresh();});};}
 return {session,data,loading,busy,error,pending:!!pending.current,retry:()=>pending.current&&void run(pending.current),refresh:()=>void run(refresh),setOffice:setter('office'),setAcademic:setter('academic'),setFinance:setter('finance'),logout:async()=>{await supabase.auth.signOut();setData(null);}};
}
export function AccessScreen(){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{if(window.location.hash.includes('type=recovery')||new URLSearchParams(window.location.search).has('recuperar'))setMode('password');},[]);
async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{let error;if(mode==='login')({error}=await supabase.auth.signInWithPassword({email,password}));else if(mode==='create'){({error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}}));if(!error)setMessage('Consulte o email para confirmar a conta. Depois, volte e entre com a palavra-passe.');}else if(mode==='recover'){setMessage('Contacte o Administrador para receber um novo link individual de acesso. O envio automático de email ainda não está configurado.');}else{({error}=await supabase.auth.updateUser({password}));if(!error){setMessage('Palavra-passe atualizada.');window.location.assign('/');}}if(error)throw error;}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
return <main className="auth-page"><section className="auth-story"><div className="auth-story-copy"><span className="eyebrow">BEZA INOVAÇÕES</span><h1>A tua formação<br/>começa aqui.</h1><p>Construção & Formação</p></div></section><section className="auth-form-side"><div className="auth-box"><span className="orange-label">CENTRO DE FORMAÇÃO</span><h2>{mode==='login'?'Aceder ao centro':mode==='create'?'Ativar a minha conta':mode==='recover'?'Recuperar acesso':'Nova palavra-passe'}</h2><p>Usa o email autorizado pelo Administrador. No primeiro acesso, pede ao Administrador o teu link de ativação. A pré-inscrição pública não exige conta.</p><form onSubmit={submit}>{mode!=='password'&&<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='recover'&&<label>Palavra-passe<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<Button className="primary" disabled={busy}>{busy?'Aguarda…':mode==='login'?'Entrar':mode==='create'?'Criar conta e confirmar email':mode==='recover'?'Como recuperar o acesso':'Guardar palavra-passe'}</Button></form>{message&&<p role="status">{message}</p>}<div className="office-actions">{['login','recover'].filter(m=>m!==mode).map(m=><Button key={m} variant="ghost" onClick={()=>{setMode(m);setMessage('');}}>{m==='login'?'Entrar':m==='create'?'Primeiro acesso':'Esqueci a palavra-passe'}</Button>)}</div><a href="/inscricao">Fazer pré-inscrição num curso →</a></div></section></main>;
}
export function RemoteAttachment({path,label}:{path:string;label:string}){const [url,setURL]=useState(''),[error,setError]=useState('');useEffect(()=>{let live=true;supabase.storage.from('centro-documentos').createSignedUrl(path,120).then(({data,error})=>{if(live){if(error)setError('Não foi possível abrir o documento. Feche e tente novamente.');else setURL(data.signedUrl);}});return()=>{live=false;};},[path]);return error?<p role="alert">{error}</p>:url?<><a href={url} target="_blank" rel="noreferrer">Abrir {label}</a><iframe title={label} src={url} style={{width:'100%',height:'60vh',border:0}}/></>:<p>A carregar documento…</p>;}
export function AccessManagement({office}:{office:Office}){type Access={email:string;name:string;role:string;person_id:string|null;active:boolean};const [links,setLinks]=useState<Record<string,string>>({});const [list,setList]=useState<Access[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Access>({email:'',name:'',role:'Secretaria',person_id:'',active:true});const load=()=>rpc<Access[]>('centro_access_list').then(setList).catch(e=>setError(e.message));useEffect(()=>{void load();},[]);return <section className="panel" style={{padding:24}}><h1>Utilizadores</h1><p>Autorize o email e o perfil. Depois gere um link individual de ativação e entregue-o à pessoa. O link permite definir a palavra-passe; trate-o como confidencial.</p><form className="office-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await rpc('centro_access_save',{p_email:draft.email,p_name:draft.name,p_role:draft.role,p_person:draft.role==='Formador'?(draft.person_id||crypto.randomUUID()):draft.person_id,p_active:draft.active});await load();setError('Acesso guardado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Nome<input required minLength={3} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Email<input required type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Perfil<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value,person_id:''})}>{['Administrador','Secretaria','Formador','Financeiro','Aluno'].map(r=><option key={r}>{r}</option>)}</select></label>{draft.role==='Aluno'&&<label>Ficha do aluno<select required value={draft.person_id||''} onChange={e=>setDraft({...draft,person_id:e.target.value})}><option value="">Selecionar</option>{office.students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.documentNumber}</option>)}</select></label>}<label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Acesso ativo</label><Button disabled={busy} className="primary">Guardar acesso</Button></form>{error&&<p role="status">{error}</p>}<ul>{list.map(a=><li key={a.email}><Button variant="ghost" onClick={()=>setDraft(a)}>{a.name} · {a.email} · {a.role} · {a.active?'Ativo':'Suspenso'}</Button>{a.active&&<Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{const {data,error}=await supabase.functions.invoke('centro-acesso',{body:{email:a.email}});if(error)throw new Error('Não foi possível gerar o link. Tente novamente.');setLinks(v=>({...v,[a.email]:data.url}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Gerar link de acesso</Button>}{links[a.email]&&<p><a href={links[a.email]} target="_blank" rel="noreferrer">Link individual de {a.name}</a></p>}</li>)}</ul></section>;}
