'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {rpc} from '@/lib/supabase';
import type {Office} from '@/lib/office';
import {certificateDocument,type CertificateListing,type CertificateCheck,type IssuedCertificate} from '@/lib/certificates';
import type {DocumentData} from '@/lib/documents';
import {OfficeModal} from './office';
import DocumentViewer from './document-viewer';
import './finance.css';

export default function Certificates({role,office}:{role:string;office:Office}){
 const [data,setData]=useState<CertificateListing|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[policy,setPolicy]=useState(false),[document,setDocument]=useState<DocumentData|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{let cancelled=false;setError('');setData(null);rpc<CertificateListing>('centro_certificate_list').then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[attempt]);
 const student=role==='Aluno';
 const entries=office.entries.filter(e=>e.status==='Confirmada'&&`${office.students.find(s=>s.id===e.studentId)?.name} ${office.courses.find(c=>c.id===e.courseId)?.name} ${e.reference}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <section className="office finance"><div className="office-heading"><div><span className="eyebrow">BEZA · {role.toUpperCase()}</span><h1>{student?'Os meus certificados':'Conclusão e certificados'}</h1><p>{student?'Consulte e descarregue os certificados emitidos pelo centro.':'Confira o percurso do formando e confirme a conclusão para emitir o certificado.'}</p></div>{role==='Administrador'&&data&&<Button type="button" variant="outline" onClick={()=>setPolicy(true)}>Definir critérios</Button>}</div>
 {notice&&<p role="status" className="office-feedback">{notice}</p>}{error?<div role="alert"><p className="office-error">{error}</p><Button type="button" onClick={()=>setAttempt(a=>a+1)}>Tentar novamente</Button></div>:!data?<p role="status">A consultar certificados…</p>:<>
 <p className="office-note">{data.policy.confirmed?`Critérios confirmados pelo centro: presença mínima de ${data.policy.minFrequency}% e média mínima de ${data.policy.minGrade}/20.`:'Os critérios ainda não foram confirmados pelo Administrador. A emissão permanece bloqueada.'}</p>
 <label className="office-search"><span>Pesquisar formando, curso ou matrícula</span><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, curso ou matrícula"/></label>
 <div className="finance-document-grid">{entries.map(e=>{const cert=data.certificates.find(c=>c.entryId===e.id);return <article className="finance-document-card" key={e.id}><h2>{cert?.name||office.students.find(s=>s.id===e.studentId)?.name}</h2><p>{cert?.course||office.courses.find(c=>c.id===e.courseId)?.name}</p><small>{e.reference}</small>{cert?<><span className="office-badge good">Concluído · certificado emitido</span><p>{cert.reference} · {new Date(cert.issued).toLocaleDateString('pt-PT')}</p><Button type="button" className="primary" onClick={()=>setDocument(certificateDocument(cert))}>Ver / descarregar certificado</Button><small>Os dados e critérios da emissão são preservados.</small></>:student?<p>A conclusão ainda não foi certificada pela Secretaria.</p>:<Button type="button" variant="outline" onClick={()=>setSelected(e.id)}>Analisar conclusão</Button>}</article>;})}</div>{entries.length===0&&<p className="office-empty">Nenhuma inscrição confirmada encontrada.</p>}
 {policy&&<PolicyForm data={data} close={()=>setPolicy(false)} saved={()=>{setPolicy(false);setAttempt(a=>a+1);setNotice('Critérios confirmados. Serão aplicados às próximas emissões.');}}/>}
 {selected&&<Completion key={selected} entryId={selected} close={()=>setSelected('')} issued={c=>{setData(d=>d?{...d,certificates:[c,...d.certificates.filter(x=>x.entryId!==c.entryId)]}:d);setSelected('');setNotice('Conclusão confirmada e certificado emitido: '+c.reference);setDocument(certificateDocument(c));}}/>}
 </>}{document&&<DocumentViewer data={document} close={()=>setDocument(null)}/>}</section>;
}

function PolicyForm({data,close,saved}:{data:CertificateListing;close:()=>void;saved:()=>void}){
 const [frequency,setFrequency]=useState(String(data.policy.minFrequency)),[grade,setGrade]=useState(String(data.policy.minGrade)),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setError('');if(!frequency.trim()||!grade.trim()||!Number.isFinite(Number(frequency))||!Number.isFinite(Number(grade))||Number(frequency)<0||Number(frequency)>100||Number(grade)<0||Number(grade)>20||!confirm){setError('Introduza valores válidos e confirme os critérios do centro.');return;}setBusy(true);try{await rpc('centro_certificate_policy_save',{p_frequency:Number(frequency),p_grade:Number(grade),p_confirm:true});saved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <OfficeModal title="Critérios de certificação" description="Defina os critérios do centro. Os valores iniciais são exemplos; certificados anteriores mantêm os critérios da emissão." close={()=>{if(!busy)close();}}><form className="office-form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:16}}><label className="office-field">Presença mínima (%)<Input type="number" required min={0} max={100} step="0.01" value={frequency} onChange={e=>{setFrequency(e.target.value);setConfirm(false);}}/></label><label className="office-field">Média mínima (0–20)<Input type="number" required min={0} max={20} step="0.01" value={grade} onChange={e=>{setGrade(e.target.value);setConfirm(false);}}/></label><label className="finance-checkbox"><Checkbox checked={confirm} onCheckedChange={v=>setConfirm(v===true)}/>Confirmo que estes são os critérios de certificação adotados pelo centro.</label>{error&&<p className="office-error" role="alert">{error}</p>}<Button type="submit" className="primary" disabled={!confirm}>{busy?'A guardar…':'Confirmar critérios'}</Button></fieldset></form></OfficeModal>;
}

function Completion({entryId,close,issued}:{entryId:string;close:()=>void;issued:(c:IssuedCertificate)=>void}){
 const [check,setCheck]=useState<CertificateCheck|null>(null),[attempt,setAttempt]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{let cancelled=false;setCheck(null);setError('');setConfirmed(false);rpc<CertificateCheck>('centro_certificate_check',{p_entry:entryId}).then(d=>{if(!cancelled)setCheck(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[entryId,attempt]);
 async function issue(){setBusy(true);setError('');try{issued(await rpc<IssuedCertificate>('centro_certificate_issue',{p_entry:entryId,p_completed:confirmed}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <OfficeModal title="Confirmar conclusão" description="A emissão volta a verificar os dados guardados no centro e regista a sua confirmação no histórico." close={()=>{if(!busy)close();}}>{check?<><h2>{check.name}</h2><p>{check.course} · {check.cohort||'Sem turma'}</p><dl className="office-details">{[['Frequência',check.frequency===null?'Sem registo':check.frequency.toFixed(2)+'%'],['Média',check.average===null?'Sem registo':check.average.toFixed(2)+'/20'],['Carga horária',check.hours?check.hours+' horas':'Por definir'],['Fim da turma',check.endDate?new Date(check.endDate+'T12:00:00').toLocaleDateString('pt-PT'):'Por definir']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{check.reasons.length>0?<ul className="finance-requirements">{check.reasons.map(r=><li key={r}>{r}</li>)}</ul>:<label className="finance-checkbox"><Checkbox checked={confirmed} disabled={busy} onCheckedChange={v=>setConfirmed(v===true)}/>Conferi as presenças e avaliações e confirmo que o formando concluiu a formação.</label>}<Button type="button" className="primary" disabled={busy||!confirmed||!!check.reasons.length} onClick={issue}>{busy?'A emitir…':'Confirmar conclusão e emitir'}</Button></>:!error&&<p role="status">A conferir os registos…</p>}{error&&<p className="office-error" role="alert">{error}</p>}<Button type="button" variant="outline" disabled={busy} onClick={()=>setAttempt(a=>a+1)}>Atualizar análise</Button></OfficeModal>;
}
