'use client';
import {useState,useRef,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {OfficeModal} from './office';
import {emptyRegistration,genders,periods,todayISO,validateFile,type Documents,type DocumentKind} from '@/lib/registration';
import {normalize,type Office,type Student} from '@/lib/office';
import {enrolmentErrors,type EnrolmentDraft} from '@/lib/office-enrolment';
const labels={photo:'Fotografia',identity:'BI / Passaporte',payment:'Comprovativo de pagamento'};
export function EnrolmentAttachment({file,label}:{file:File;label:string}){const [url,setURL]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setURL(u);return()=>URL.revokeObjectURL(u);},[file]);return <>{url&&(file.name.toLowerCase().endsWith('.pdf')?<iframe className="finance-pdf" title={label} src={url}/>:<img src={url} alt={label} style={{maxHeight:'55vh',maxWidth:'100%',objectFit:'contain',margin:'auto'}}/>)}<p>{file.name}</p></>;}
function Choice({label,value,options,change}:{label:string;value:string;options:{id:string;name:string}[];change:(s:string)=>void}){return <label className="office-field">{label}<Select value={value||null} onValueChange={v=>{if(v!==null)change(v);}}><SelectTrigger aria-label={label}><SelectValue placeholder="Seleciona"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></label>;}
export default function NewEnrolment({state,close,save}:{state:Office;close:()=>void;save:(draft:EnrolmentDraft)=>void}){
 const [mode,setMode]=useState('new'),[student,setStudent]=useState<Student>({...emptyRegistration,id:crypto.randomUUID()}),[person,setPerson]=useState(''),[search,setSearch]=useState(''),[courseId,setCourse]=useState(''),[period,setPeriod]=useState(''),[startDate,setStart]=useState(todayISO()),[files,setFiles]=useState<Documents>({photo:null,identity:null,payment:null}),[errors,setErrors]=useState<Record<string,string>>({}),[busy,setBusy]=useState<Record<string,boolean>>({});
 const versions=useRef<Record<string,number>>({}),summary=useRef<HTMLDivElement>(null),saving=useRef(false);
 const selected=state.students.find(s=>s.id===person),checking=Object.values(busy).some(Boolean);
 useEffect(()=>{if(Object.keys(errors).length)summary.current?.focus();},[errors]);
 async function attach(kind:DocumentKind,file:File){const version=(versions.current[kind]||0)+1;versions.current[kind]=version;setBusy(s=>({...s,[kind]:true}));setFiles(s=>({...s,[kind]:null}));try{const error=await validateFile(file,kind);if(error)throw new Error(error);if(!file.name.toLowerCase().endsWith('.pdf')){const bitmap=await createImageBitmap(file);bitmap.close();}if(versions.current[kind]===version){setFiles(s=>({...s,[kind]:file}));setErrors(s=>{const next={...s};delete next[kind];return next;});}}catch(e){if(versions.current[kind]===version)setErrors(s=>({...s,[kind]:(e as Error).message}));}finally{if(versions.current[kind]===version)setBusy(s=>({...s,[kind]:false}));}}
 function submit(){if(checking||saving.current)return;const d={student:mode==='existing'?(selected||{...student,id:''}):student,existing:mode==='existing',courseId,period,startDate,files};const e=enrolmentErrors(state,d);setErrors(e);if(Object.keys(e).length)return;saving.current=true;try{save(d);}catch(err){saving.current=false;setErrors({save:(err as Error).message});}}
 return <OfficeModal title="Nova inscrição" description="Regista um formando no atendimento. Anexe os documentos e o comprovativo de pagamento." close={close}><form className="office-form" noValidate onSubmit={e=>{e.preventDefault();submit();}}>{Object.keys(errors).length>0&&<div ref={summary} tabIndex={-1} role="alert" className="office-error"><strong>Revê os dados:</strong><ul>{Object.entries(errors).map(([k,v])=><li key={k}>{v}</li>)}</ul></div>}
 <Choice label="Formando" value={mode} options={[{id:'new',name:'Novo aluno'},{id:'existing',name:'Aluno já registado'}]} change={v=>{setMode(v);setErrors({});}}/>
 {mode==='existing'?<><label className="office-field">Pesquisar aluno por nome ou BI<Input value={search} onChange={e=>setSearch(e.target.value)}/></label><Choice label="Ficha do aluno" value={person} options={state.students.filter(s=>s.id===person||normalize(s.name+' '+s.documentNumber).includes(normalize(search))).map(s=>({id:s.id,name:s.name+' · '+s.documentNumber}))} change={setPerson}/>{selected&&<p>{selected.phone} · A ficha existente será preservada.</p>}</>:<><div className="academic-two">{([['name','Nome completo','text'],['birthDate','Data de nascimento','date'],['nationality','Nacionalidade','text'],['documentNumber','Número do BI / Passaporte','text'],['phone','Telefone','tel'],['address','Morada','text']] as const).map(([k,label,type])=><label className="office-field" key={k}>{label}<Input aria-invalid={!!errors[k]} value={student[k]} type={type} max={k==='birthDate'?todayISO():undefined} maxLength={k==='address'?250:150} onChange={e=>setStudent(s=>({...s,[k]:e.target.value}))}/></label>)}</div><Choice label="Género" value={student.gender} options={genders.map(x=>({id:x,name:x}))} change={gender=>setStudent(s=>({...s,gender}))}/><Choice label="Tipo de documento" value={student.documentType} options={['BI','Passaporte'].map(x=>({id:x,name:x}))} change={documentType=>setStudent(s=>({...s,documentType}))}/></>}
 <Choice label="Curso" value={courseId} options={state.courses.filter(c=>c.active).map(c=>({id:c.id,name:c.name}))} change={setCourse}/><Choice label="Período" value={period} options={periods.map(x=>({id:x,name:x}))} change={setPeriod}/><label className="office-field">Início pretendido<Input type="date" min={todayISO()} value={startDate} onChange={e=>setStart(e.target.value)}/></label>
 <fieldset className="office-form"><legend>Documentos obrigatórios · até 5 MB por ficheiro</legend>{(Object.keys(labels) as DocumentKind[]).map(kind=><label key={kind} className="office-field">{labels[kind]} · {kind==='photo'?'JPG ou PNG':'JPG, PNG ou PDF'}<Input type="file" accept={kind==='photo'?'.jpg,.jpeg,.png':'.jpg,.jpeg,.png,.pdf'} aria-invalid={!!errors[kind]} onChange={e=>{const f=e.target.files?.[0];if(f)void attach(kind,f);e.target.value='';}}/>{busy[kind]?<small role="status">A verificar…</small>:files[kind]&&<small>{files[kind]!.name}</small>}</label>)}</fieldset>
 <p className="office-note">A inscrição e os anexos serão guardados no centro. A matrícula será atribuída após análise e aprovação; o comprovativo não regista automaticamente um pagamento.</p><div className="office-actions"><Button type="button" variant="outline" onClick={close}>Cancelar</Button><Button className="primary" type="submit" disabled={checking}>{checking?'A verificar documentos…':'Guardar inscrição'}</Button></div></form></OfficeModal>;
}
