'use client';
import {useState,type Dispatch,type SetStateAction,type ReactNode} from 'react';
import {Search,Plus,ArrowRight,CheckCircle2,XCircle,FileText,Users,BookOpen,Pencil,X,Eye} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {courseGroups,genders,periods,formatDate} from '@/lib/registration';
import {normalize,courseErrors,studentErrors,decideEntry,type Office,type Course,type Student,type Entry} from '@/lib/office';
import './office.css';
import {RemoteAttachment} from './backend';
import EnrolmentActions from './enrolment-actions';
import NewEnrolment,{EnrolmentAttachment} from './new-enrolment';
import {createOfficeEnrolment,type EnrolmentDraft} from '@/lib/office-enrolment';

function Pick({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <label className="office-filter"><span>{label}</span><Select value={value||null} onValueChange={v=>{if(v!==null)onChange(v);}}><SelectTrigger aria-label={label}><SelectValue placeholder="Seleciona"/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>;}
function Badge({status}:{status:string}){return <span className={'office-badge '+(status==='Confirmada'||status==='Ativo'?'good':status==='Rejeitada'||status==='Inativo'?'bad':'wait')}>{status}</span>;}
function Modal({title,description,close,children}:{title:string;description:string;close:()=>void;children:ReactNode}){return <Dialog open onOpenChange={v=>{if(!v)close();}}><DialogContent className="office-modal" showCloseButton={false}><div className="office-modal-title"><div><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></div><Button variant="ghost" onClick={close} aria-label="Fechar"><X/></Button></div>{children}</DialogContent></Dialog>;}
function FormField({label,children,error}:{label:string;children:ReactNode;error?:string}){return <label className="office-field"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>;}
const money=(n:string)=>n===''?'Por definir':new Intl.NumberFormat('pt-AO',{style:'currency',currency:'AOA'}).format(Number(n));
const when=(date:string)=>new Date(date).toLocaleString('pt-AO');
export default function OfficeModule({page,role,state,setState}:{page:string;role:string;state:Office;setState:Dispatch<SetStateAction<Office>>}){
 const [creating,setCreating]=useState(false);
 const [query,setQuery]=useState(''),[status,setStatus]=useState('Pendente'),[courseFilter,setCourseFilter]=useState('Todos os cursos'),[period,setPeriod]=useState('Todos os períodos'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[category,setCategory]=useState('Todas as categorias'),[activity,setActivity]=useState('Todos'),[offset,setOffset]=useState(1);
 const [selected,setSelected]=useState<string|null>(null),[person,setPerson]=useState<string|null>(null),[studentDraft,setStudentDraft]=useState<Student|null>(null),[courseDraft,setCourseDraft]=useState<Course|null>(null),[errors,setErrors]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[decision,setDecision]=useState<'Confirmada'|'Rejeitada'|null>(null),[reason,setReason]=useState(''),[review,setReview]=useState(false),[toggle,setToggle]=useState<Course|null>(null),[document,setDocument]=useState<string|null>(null);
 const entry=state.entries.find(e=>e.id===selected),student=state.students.find(s=>s.id===(entry?.studentId||person));
 const courseName=(e:Entry)=>state.courses.find(c=>c.id===e.courseId)?.name||e.requestedCourse||'Curso a associar';
 const entryList=state.entries.filter(e=>{const s=state.students.find(s=>s.id===e.studentId)!;return (status==='Todos os estados'||e.status===status)&&(courseFilter==='Todos os cursos'||courseName(e)===courseFilter)&&(period==='Todos os períodos'||e.period===period)&&(!from||e.date.slice(0,10)>=from)&&(!to||e.date.slice(0,10)<=to)&&normalize(`${s.name} ${s.documentNumber} ${e.id}`).includes(normalize(query));}).sort((a,b)=>a.date.localeCompare(b.date));
 const studentList=state.students.filter(s=>normalize(`${s.name} ${s.documentNumber}`).includes(normalize(query)));
 const courseList=state.courses.filter(c=>normalize(c.name).includes(normalize(query))&&(category==='Todas as categorias'||c.category===category)&&(activity==='Todos'||(activity==='Ativos')===c.active));
 const total=page==='Inscrições'?entryList.length:page==='Alunos'?studentList.length:courseList.length;const maxPage=Math.max(1,Math.ceil(total/8)),current=Math.min(offset,maxPage);const slice=<T,>(list:T[])=>list.slice((current-1)*8,current*8);
 function filter(action:()=>void){action();setOffset(1);}
 function openEntry(id:string){setSelected(id);setPerson(null);setReview(false);setErrors({});setReason('');}
 function closeDetails(){setSelected(null);setPerson(null);setDecision(null);setReview(false);setErrors({});}
 function decide(){if(!entry||!decision)return;try{if(decision==='Confirmada'&&!review)throw new Error('Confirma a conferência dos dados e dos três documentos.');const next=decideEntry(state,entry.id,decision,reason,role,new Date().toISOString());setState(next);setDecision(null);setErrors({});setNotice(decision==='Confirmada'?'Pedido de confirmação enviado. Aguarde a conclusão da gravação.':'Inscrição rejeitada. Motivo registado.');}catch(e){setErrors({decision:(e as Error).message});}}
 function saveCourse(){if(!courseDraft)return;const e=courseErrors(courseDraft,state.courses);setErrors(e);if(Object.keys(e).length)return;setState(s=>({...s,courses:s.courses.some(c=>c.id===courseDraft.id)?s.courses.map(c=>c.id===courseDraft.id?{...courseDraft,name:courseDraft.name.trim(),duration:courseDraft.duration.trim()}:c):[...s.courses,{...courseDraft,name:courseDraft.name.trim()}]}));setCourseDraft(null);setNotice('Curso guardado.');}
 function saveStudent(){if(!studentDraft)return;const e=studentErrors(studentDraft,state.students);setErrors(e as Record<string,string>);if(Object.keys(e).length)return;setState(s=>({...s,students:s.students.map(p=>p.id===studentDraft.id?{...studentDraft,name:studentDraft.name.trim(),documentNumber:studentDraft.documentNumber.trim()}:p)}));setStudentDraft(null);setReview(false);setNotice('Ficha atualizada.');}
 function create(d:EnrolmentDraft){const id='PRE-DEMO-'+crypto.randomUUID();const next=createOfficeEnrolment(state,d,role,id,new Date().toISOString());setState(next);setCreating(false);setQuery('');setStatus('Pendente');setCourseFilter('Todos os cursos');setPeriod('Todos os períodos');setFrom('');setTo('');setOffset(Math.ceil(next.entries.filter(e=>e.status==='Pendente').length/8));openEntry(id);setNotice('Inscrição criada e adicionada à fila de análise. Aguarde a conclusão da gravação no centro.');}
 const subheading=page==='Inscrições'?'Regista novos formandos, confere os documentos e acompanha cada inscrição.':page==='Alunos'?'Uma ficha por BI ou Passaporte, com todas as inscrições associadas.':'Organiza o catálogo, a duração, a carga horária e o preço de cada formação.';
 return <div className="office"><div className="office-heading"><div><span className="eyebrow">SECRETARIA · GESTÃO DO CENTRO</span><h1>{page==='Inscrições'?'Inscrições de formandos':page==='Alunos'?'Alunos e percursos':'Catálogo de cursos'}</h1><p>{subheading}</p></div>{page==='Inscrições'&&<Button className="primary" onClick={()=>setCreating(true)}><Plus size={18}/>Nova inscrição</Button>}{page==='Cursos'&&<Button className="primary" onClick={()=>{setErrors({});setCourseDraft({id:crypto.randomUUID(),name:'',category:'Administrativos',duration:'',hours:'',price:'',active:true});}}><Plus size={18}/>Novo curso</Button>}</div>
 <div className="office-note">Os registos são guardados no centro. Analise os documentos antes de confirmar cada inscrição.</div>
 {notice&&<div className="office-feedback" role="status">{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="office-summary">{(page==='Inscrições'?[['Pendentes',state.entries.filter(e=>e.status==='Pendente').length],['Confirmadas',state.entries.filter(e=>e.status==='Confirmada').length],['Rejeitadas',state.entries.filter(e=>e.status==='Rejeitada').length]]:page==='Alunos'?[['Alunos',state.students.length],['Inscrições',state.entries.length],['Com vários cursos',state.students.filter(s=>state.entries.filter(e=>e.studentId===s.id).length>1).length]]:[['Cursos',state.courses.length],['Ativos',state.courses.filter(c=>c.active).length],['Categorias',4]]).map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong></div>)}</div>
 <section className="office-surface"><div className="office-filters"><label className="office-search"><span>{page==='Cursos'?'Pesquisar curso':'Pesquisar por nome ou BI/Passaporte'}</span><div><Search size={18}/><Input value={query} onChange={e=>filter(()=>setQuery(e.target.value))} placeholder={page==='Cursos'?'Nome do curso':'Ex.: Ana ou DEMO10001'} aria-label={page==='Cursos'?'Pesquisar curso':'Pesquisar por nome ou BI/Passaporte'}/></div></label>
 {page==='Inscrições'&&<><Pick label="Estado" value={status} values={['Todos os estados','Pendente','Confirmada','Rejeitada']} onChange={v=>filter(()=>setStatus(v))}/><Pick label="Curso" value={courseFilter} values={['Todos os cursos',...Array.from(new Set(state.entries.map(courseName)))]} onChange={v=>filter(()=>setCourseFilter(v))}/><Pick label="Período" value={period} values={['Todos os períodos',...periods]} onChange={v=>filter(()=>setPeriod(v))}/><label className="office-filter">Recebida desde<Input type="date" aria-label="Recebida desde" value={from} max={to||undefined} onChange={e=>filter(()=>setFrom(e.target.value))}/></label><label className="office-filter">Recebida até<Input type="date" aria-label="Recebida até" value={to} min={from||undefined} onChange={e=>filter(()=>setTo(e.target.value))}/></label></>}
 {page==='Cursos'&&<><Pick label="Categoria" value={category} values={['Todas as categorias',...courseGroups.map(g=>g.name)]} onChange={v=>filter(()=>setCategory(v))}/><Pick label="Disponibilidade" value={activity} values={['Todos','Ativos','Inativos']} onChange={v=>filter(()=>setActivity(v))}/></>}
 <Button variant="ghost" onClick={()=>{setQuery('');setStatus('Todos os estados');setCourseFilter('Todos os cursos');setPeriod('Todos os períodos');setFrom('');setTo('');setCategory('Todas as categorias');setActivity('Todos');setOffset(1);}}>Limpar filtros</Button></div>
 {from&&to&&from>to&&<p className="office-error" role="alert">A data inicial não pode ser posterior à data final.</p>}
 {total===0?<div className="office-empty"><Search size={30}/><h2>Nenhum resultado encontrado</h2><p>Revê o texto pesquisado ou limpa os filtros.</p></div>:<Table><TableHeader><TableRow>{(page==='Inscrições'?['Formando / BI','Curso / período','Recebida em','Estado','']:page==='Alunos'?['Aluno','BI / Passaporte','Telefone','Inscrições','']:['Curso / categoria','Duração / horas','Preço','Estado','']).map((h,i)=><TableHead key={i}>{h||<span className="sr-only">Ações</span>}</TableHead>)}</TableRow></TableHeader><TableBody>
 {page==='Inscrições'&&slice(entryList).map(e=>{const s=state.students.find(s=>s.id===e.studentId)!;return <TableRow key={e.id}><TableCell><strong>{s.name}</strong><small>{s.documentNumber}</small></TableCell><TableCell><strong>{courseName(e)}</strong><small>{e.period}{!e.courseId?' · Curso por associar':''}</small></TableCell><TableCell>{formatDate(e.date.slice(0,10))}<small>{e.id}</small></TableCell><TableCell><Badge status={e.status}/></TableCell><TableCell><Button variant="outline" onClick={()=>openEntry(e.id)}>Analisar<ArrowRight size={16}/></Button></TableCell></TableRow>;})}
 {page==='Alunos'&&slice(studentList).map(s=><TableRow key={s.id}><TableCell><strong>{s.name}</strong><small>{s.nationality}</small></TableCell><TableCell>{s.documentNumber}</TableCell><TableCell>{s.phone}</TableCell><TableCell>{state.entries.filter(e=>e.studentId===s.id).length}</TableCell><TableCell><Button variant="outline" onClick={()=>{setPerson(s.id);setSelected(null);}}>Abrir ficha<ArrowRight size={16}/></Button></TableCell></TableRow>)}
 {page==='Cursos'&&slice(courseList).map(c=><TableRow key={c.id}><TableCell><strong>{c.name}</strong><small>{c.category}</small></TableCell><TableCell>{c.duration||'Por definir'}<small>{c.hours?`${c.hours} horas`:'Carga horária por definir'}</small></TableCell><TableCell>{money(c.price)}</TableCell><TableCell><Badge status={c.active?'Ativo':'Inativo'}/></TableCell><TableCell><div className="office-actions"><Button variant="outline" onClick={()=>{setErrors({});setCourseDraft({...c});}}><Pencil size={16}/>Editar</Button><Button variant="ghost" onClick={()=>setToggle(c)}>{c.active?'Desativar':'Ativar'}</Button></div></TableCell></TableRow>)}
 </TableBody></Table>}
 <div className="office-pagination"><span aria-live="polite">{total} {total===1?'resultado':'resultados'} · Página {current} de {maxPage}</span><Pagination><PaginationContent><PaginationItem><Button variant="outline" disabled={current===1} onClick={()=>setOffset(current-1)} aria-label="Página anterior">Anterior</Button></PaginationItem><PaginationItem><Button variant="outline" disabled={current===maxPage} onClick={()=>setOffset(current+1)} aria-label="Página seguinte">Seguinte</Button></PaginationItem></PaginationContent></Pagination></div></section>
 {creating&&<NewEnrolment state={state} close={()=>setCreating(false)} save={create}/>}
 {student&&(entry||person)&&<Modal title={entry?'Analisar pré-inscrição':'Ficha do aluno'} description={entry?entry.id:'Identificação · '+student.documentNumber} close={closeDetails}><div className="office-detail-head"><div className="office-person-icon"><Users size={26}/></div><div><h2>{student.name}</h2><p>{student.documentType} · {student.documentNumber}</p></div>{entry&&<Badge status={entry.status}/>}<Button variant="outline" onClick={()=>{setErrors({});setStudentDraft({...student});}}><Pencil size={16}/>Editar ficha</Button></div><dl className="office-details">{[['Nascimento',formatDate(student.birthDate)],['Género',student.gender],['Nacionalidade',student.nationality],['Telefone',student.phone],['Morada',student.address]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 {entry?<>{entry.submitted&&<section className="office-detail-section"><h3>Dados enviados neste pedido</h3><p>Confira estes dados com os anexos. Uma ficha já existente é preservada.</p><dl className="office-details">{[["Nome",entry.submitted.name],["Documento",entry.submitted.documentNumber],["Telefone",entry.submitted.phone],["Morada",entry.submitted.address]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}<section className="office-detail-section"><h3>Curso pretendido</h3><strong>{courseName(entry)}</strong><p>{entry.period} · Início pretendido: {formatDate(entry.startDate)}</p>{entry.requestedCourse&&<p>Pedido original: {entry.requestedCourse}</p>}{entry.status==='Pendente'&&<label className="office-filter"><span>Associar ou corrigir curso</span><Select value={entry.courseId||null} onValueChange={v=>{if(v){setState(s=>({...s,entries:s.entries.map(e=>e.id===entry.id?{...e,courseId:v}:e)}));setReview(false);}}}><SelectTrigger aria-label="Associar curso ativo"><SelectValue placeholder="Seleciona um curso ativo"/></SelectTrigger><SelectContent>{state.courses.filter(c=>c.active).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label>}</section><section className="office-detail-section"><h3>Documentos para conferência</h3><p>Abra e confira os três ficheiros enviados.</p><div className="office-docs">{['Fotografia','BI / Passaporte','Comprovativo de pagamento'].map(label=><Button variant="outline" key={label} onClick={()=>setDocument(label)}><FileText size={18}/>{label}<Eye size={16}/></Button>)}</div></section>
 {entry.status==='Pendente'?<section className="office-decision"><label><Checkbox checked={review} onCheckedChange={v=>setReview(v===true)}/><span>Conferi os dados, a fotografia, o documento de identificação e o comprovativo de pagamento.</span></label><div className="office-actions"><Button className="primary" disabled={!review||!state.courses.some(c=>c.id===entry.courseId&&c.active)} onClick={()=>{setErrors({});setDecision('Confirmada');}}><CheckCircle2 size={18}/>Confirmar inscrição</Button><Button variant="outline" onClick={()=>{setErrors({});setDecision('Rejeitada');}}><XCircle size={18}/>Rejeitar inscrição</Button></div>{!state.courses.some(c=>c.id===entry.courseId&&c.active)&&<p className="office-error">Associa um curso ativo antes de confirmar.</p>}</section>:<section className="office-result"><h3>{entry.status==='Confirmada'?'Matrícula': 'Motivo da rejeição'}</h3><strong>{entry.status==='Confirmada'?entry.reference:entry.reason}</strong><EnrolmentActions key={entry.id} entry={entry} name={student.name} phone={student.phone} course={courseName(entry)}/></section>}
 <section className="office-detail-section"><h3>Histórico desta inscrição</h3><ul className="office-history">{entry.history.map((h,i)=><li key={i}><strong>{h.action}</strong><small>{h.actor} · {when(h.date)}</small></li>)}</ul></section></>:<section className="office-detail-section"><h3>Todas as inscrições deste BI</h3><div className="office-enrolments">{state.entries.filter(e=>e.studentId===student.id).map(e=><button key={e.id} onClick={()=>openEntry(e.id)}><div><strong>{courseName(e)}</strong><small>{e.period} · {e.reference||e.id}</small></div><Badge status={e.status}/><ArrowRight size={16}/></button>)}</div></section>}
 <Button variant="outline" onClick={closeDetails}>Fechar</Button></Modal>}
 {document&&<Modal title={document} description="Documento anexado à inscrição" close={()=>setDocument(null)}>{entry?.paths?.[document==='Fotografia'?'photo':document==='BI / Passaporte'?'identity':'payment']?<RemoteAttachment path={entry.paths[document==='Fotografia'?'photo':document==='BI / Passaporte'?'identity':'payment']} label={document}/>:entry?.attachments?.[document==='Fotografia'?'photo':document==='BI / Passaporte'?'identity':'payment']?<EnrolmentAttachment file={entry.attachments[document==='Fotografia'?'photo':document==='BI / Passaporte'?'identity':'payment']!} label={document}/>:<div className="office-document-sample"><FileText size={44}/><h2>EXEMPLO · SEM VALIDADE</h2><p>{document}</p><p>Este espaço apresentará o ficheiro anexado pelo formando após a integração com o Supabase.</p><strong>Não contém dados nem comprovativos reais.</strong></div>}<Button variant="outline" onClick={()=>setDocument(null)}>Voltar à análise</Button></Modal>}
 {decision&&entry&&<Modal title={decision==='Confirmada'?'Confirmar esta inscrição?':'Rejeitar esta inscrição?'} description={`${student?.name} · ${courseName(entry)}`} close={()=>setDecision(null)}><p>{decision==='Confirmada'?'A inscrição será confirmada após a verificação dos documentos.':'Indica um motivo claro para ficar registado no histórico.'}</p>{decision==='Rejeitada'&&<FormField label="Motivo da rejeição" error={errors.decision}><Textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={4} aria-label="Motivo da rejeição"/></FormField>}{decision==='Confirmada'&&errors.decision&&<p role="alert" className="office-error">{errors.decision}</p>}<div className="office-actions"><Button variant="outline" onClick={()=>setDecision(null)}>Cancelar</Button><Button className="primary" onClick={decide}>Concluir simulação</Button></div></Modal>}
 {courseDraft&&<Modal title={state.courses.some(c=>c.id===courseDraft.id)?'Editar curso':'Novo curso'} description="Todos os campos são obrigatórios. Preços em Kwanza (AOA)." close={()=>setCourseDraft(null)}><form onSubmit={e=>{e.preventDefault();saveCourse();}} noValidate className="office-form"><FormField label="Nome do curso" error={errors.name}><Input aria-label="Nome do curso" value={courseDraft.name} maxLength={150} onChange={e=>setCourseDraft({...courseDraft,name:e.target.value})}/></FormField><Pick label="Categoria" value={courseDraft.category} values={courseGroups.map(g=>g.name)} onChange={v=>setCourseDraft({...courseDraft,category:v})}/><FormField label="Duração (ex.: 3 meses)" error={errors.duration}><Input aria-label="Duração" value={courseDraft.duration} maxLength={80} onChange={e=>setCourseDraft({...courseDraft,duration:e.target.value})}/></FormField><FormField label="Carga horária (horas)" error={errors.hours}><Input aria-label="Carga horária" type="number" min={1} max={10000} value={courseDraft.hours} onChange={e=>setCourseDraft({...courseDraft,hours:e.target.value})}/></FormField><FormField label="Preço (AOA)" error={errors.price}><Input aria-label="Preço em AOA" type="number" min={0} step="0.01" value={courseDraft.price} onChange={e=>setCourseDraft({...courseDraft,price:e.target.value})}/></FormField><p className="office-note">Sem limite de vagas. Os valores dos cursos existentes estão por definir até serem preenchidos pelo centro.</p><div className="office-actions"><Button type="button" variant="outline" onClick={()=>setCourseDraft(null)}>Cancelar</Button><Button type="submit" className="primary">Guardar curso</Button></div></form></Modal>}
 {studentDraft&&<Modal title="Editar ficha do aluno" description="As alterações aplicam-se a todas as inscrições deste aluno. " close={()=>setStudentDraft(null)}><form noValidate onSubmit={e=>{e.preventDefault();saveStudent();}} className="office-form">{([['name','Nome completo','text'],['birthDate','Data de nascimento','date'],['nationality','Nacionalidade','text'],['documentNumber','Número do BI / Passaporte','text'],['phone','Telefone','tel'],['address','Morada','text']] as const).map(([key,label,type])=><FormField key={key} label={label} error={errors[key]}><Input type={type} aria-label={label} maxLength={key==='address'?250:150} value={studentDraft[key]} onChange={e=>setStudentDraft({...studentDraft,[key]:e.target.value})}/></FormField>)}<Pick label="Género" value={studentDraft.gender} values={genders} onChange={v=>setStudentDraft({...studentDraft,gender:v})}/><Pick label="Tipo de documento" value={studentDraft.documentType} values={['BI','Passaporte']} onChange={v=>setStudentDraft({...studentDraft,documentType:v})}/><div className="office-actions"><Button type="button" variant="outline" onClick={()=>setStudentDraft(null)}>Cancelar</Button><Button type="submit" className="primary">Guardar ficha</Button></div></form></Modal>}
 <AlertDialog open={!!toggle} onOpenChange={v=>{if(!v)setToggle(null);}}><AlertDialogContent><AlertDialogTitle>{toggle?.active?'Desativar curso?':'Ativar curso?'}</AlertDialogTitle><AlertDialogDescription>{toggle?.name}. {toggle?.active?'As inscrições e o histórico existentes serão preservados. O curso deixa de estar disponível para novas confirmações.':'O curso volta a estar disponível para confirmações.'}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{if(toggle){setState(s=>({...s,courses:s.courses.map(c=>c.id===toggle.id?{...c,active:!c.active}:c)}));setNotice(toggle.active?'Curso desativado.':'Curso ativado.');setToggle(null);}}}>Confirmar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}


export {Modal as OfficeModal};
