'use client';
import {useState,useEffect,useRef} from 'react';
import {useBackend,AccessScreen,AccessManagement} from './backend';
import {flushSync} from 'react-dom';
import OfficeModule from './office';
import AcademicModule from './academic';
import FinanceModule from './finance';
import {initialFinance} from '@/lib/finance';
import {initialAcademic,weekdays} from '@/lib/academic';
import {initialOffice} from '@/lib/office';
import {ArrowRight,ArrowUpRight,GraduationCap,LayoutDashboard,ClipboardList,Users,BookOpen,CalendarDays,Wallet,ChartNoAxesCombined,Settings,LogOut,Phone,MessageCircle,Clock3,CheckCheck,ChevronRight,ShieldCheck,Eye,EyeOff} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
const roles=['Administrador','Secretaria','Formador','Financeiro','Aluno'];
const menus:Record<string,string[]>={Administrador:['Visão geral','Inscrições','Alunos','Cursos','Turmas','Documentos','Certificados','Financeiro','Relatórios','Utilizadores'],Secretaria:['Visão geral','Inscrições','Alunos','Cursos','Turmas','Documentos','Certificados'],Formador:['Visão geral','Minhas turmas','Presenças','Avaliações'],Financeiro:['Visão geral','Pagamentos','Receitas','Relatórios financeiros'],Aluno:['Visão geral','Minhas inscrições','Minha frequência','Minhas notas','Meus certificados']};
const icons=[LayoutDashboard,ClipboardList,Users,BookOpen,CalendarDays,Wallet,ChartNoAxesCombined,Settings];
const students=[['AM','Ana Manuel','Secretariado Executivo e Informatizado com IA','Manhã','Pendente'],['JC','João Cassoma','Eletricidade Baixa e Média Tensão','Tarde','Confirmada'],['MF','Maria Francisco','Gestão de Recursos Humanos','Noite','Pendente'],['PN','Pedro Neto','Informática com Inteligência Artificial','Manhã','Confirmada']];
const stats:Record<string,string[][]>={Administrador:[['Inscrições pendentes','24','A aguardar análise'],['Alunos em formação','186','Em 12 turmas'],['Confirmadas hoje','08','Inscrições validadas'],['Receita do mês','1 250 000','AOA · valores de exemplo']],Secretaria:[['Inscrições pendentes','24','A aguardar análise'],['Confirmadas hoje','08','Inscrições validadas'],['Alunos registados','248','Fichas de exemplo'],['Cursos disponíveis','25','Em quatro categorias']],Formador:[['Minhas turmas','03','Turmas atribuídas'],['Meus formandos','42','Em formação'],['Aulas de hoje','02','Consultar agenda'],['Presença média','92%','Dados de exemplo']],Financeiro:[['Receita do mês','1 250 000','AOA · valores de exemplo'],['Pagamentos recebidos','38','Durante este mês'],['Propinas pendentes','12','A acompanhar'],['Valor por receber','180 000','AOA · valores de exemplo']],Aluno:[['Cursos em frequência','02','Inscrições confirmadas'],['Minha frequência','94%','Dados de exemplo'],['Média das avaliações','16','Escala demonstrativa: 0–20'],['Próxima aula','09:00','Amanhã · Sala 02']]};
const stages:Record<string,string>={Inscrições:'Etapa 3',Alunos:'Etapa 3',Cursos:'Etapa 3',Turmas:'Etapa 4',Financeiro:'Etapa 5',Relatórios:'Etapa 5',Utilizadores:'Etapa 7'};
function Brand(){return <div className="brand"><div className="brand-logo"><img src="/beza-reference.png" alt="Logótipo BEZA Inovações"/></div><div><strong>BEZA<span> INOVAÇÕES</span></strong><small>CONSTRUÇÃO & FORMAÇÃO</small></div></div>}
function Contact(){return <div className="contact"><span>Contacta o centro</span><a href="tel:947968650">947 968 650</a><a href="tel:952042462">952 042 462</a><a href="https://wa.me/351920244269" target="_blank" rel="noreferrer">WhatsApp: +351 920 244 269</a></div>}
function NavigationItem({active,onNavigate,children}:{active:boolean;onNavigate:()=>void;children:React.ReactNode}){const {setOpenMobile}=useSidebar();return <SidebarMenuButton isActive={active} aria-current={active?'page':undefined} onClick={()=>{setOpenMobile(false);onNavigate();}} className="nav-item">{children}</SidebarMenuButton>;}
export default function Home(){
const backend=useBackend();const [page,setPage]=useState('Visão geral');
if(backend.loading)return <main className="auth-form-side"><p role="status">A carregar o centro…</p></main>;
if(!backend.session || (typeof window!=='undefined'&&new URLSearchParams(window.location.search).has('recuperar')))return <AccessScreen/>;
if(!backend.data)return <main className="auth-form-side"><div><h1>Acesso ao centro</h1><p role="alert">{backend.error||'A verificar o acesso…'}</p><Button onClick={backend.refresh}>Tentar novamente</Button><Button onClick={backend.logout}>Sair</Button></div></main>;
const {role,office,academic,finance,personId,name}=backend.data;
return <SidebarProvider><a className="skip-link" href="#conteudo-principal">Saltar para o conteúdo</a><Sidebar className="beza-sidebar"><SidebarHeader><Brand/></SidebarHeader><SidebarContent><div className="nav-caption">ÁREA DE TRABALHO</div><SidebarMenu>{menus[role].map((item,i)=>{const Icon=icons[i%icons.length];return <SidebarMenuItem key={item}><NavigationItem active={page===item} onNavigate={()=>setPage(item)}><Icon size={19}/><span>{item}</span>{item==='Inscrições'&&<b className="nav-count">{office.entries.filter(e=>e.status==='Pendente').length}</b>}</NavigationItem></SidebarMenuItem>})}</SidebarMenu></SidebarContent><SidebarFooter><Contact/><button className="logout" onClick={backend.logout}><LogOut size={17}/>Terminar sessão</button></SidebarFooter></Sidebar><SidebarInset><header className="topbar"><div className="breadcrumb"><SidebarTrigger aria-label="Abrir ou fechar menu"/><span>Centro de Formação</span><ChevronRight size={14}/><strong>{page}</strong></div><div className="top-right"><a className="registration-link" href="/inscricao">Pré-inscrição pública</a><div className="profile-label"><span>{role}</span><strong>{name}</strong></div></div></header><main className="workspace" id="conteudo-principal" tabIndex={-1}>
<div className="office-actions"><Button variant="outline" disabled={backend.busy} onClick={backend.refresh}>Atualizar dados</Button><span role="status">{backend.busy?'A guardar e atualizar…':'Ligado ao centro'}</span></div>
{backend.error&&<div role="alert" className="office-error"><p>{backend.error}</p>{backend.pending&&<Button onClick={backend.retry}>Tentar guardar novamente</Button>}<p>Se outro utilizador alterou os dados, atualize a página e repita a alteração.</p></div>}
<fieldset disabled={backend.busy} style={{border:0,padding:0,minWidth:0}}>
{page==='Utilizadores'&&role==='Administrador'?<AccessManagement office={office}/>:['Inscrições','Alunos','Cursos'].includes(page)&&['Administrador','Secretaria'].includes(role)?<OfficeModule key={page} page={page} role={role} state={office} setState={backend.setOffice}/>:((role==='Financeiro')||['Financeiro','Relatórios','Documentos','Certificados','Meus certificados'].includes(page))?<FinanceModule key={role+page} page={page} role={role} office={office} academic={academic} state={finance} setState={backend.setFinance} studentId={personId}/>:page==='Turmas'||role==='Formador'||role==='Aluno'?<AcademicModule key={role+page} page={page} role={role} office={office} state={academic} setState={backend.setAcademic} trainer={personId||''} setTrainer={()=>{}} studentId={personId}/>:<><div className="page-heading"><div><span className="eyebrow">PAINEL · {role.toUpperCase()}</span><h1>Bem-vindo ao centro.</h1><p>Acompanha as inscrições e organiza a formação.</p></div></div><section className="stats-grid">{[['Inscrições pendentes',office.entries.filter(e=>e.status==='Pendente').length],['Confirmadas',office.entries.filter(e=>e.status==='Confirmada').length],['Alunos registados',office.students.length],['Cursos ativos',office.courses.filter(c=>c.active).length]].map(([label,n],i)=><article key={label} className={'stat-card '+(i===0?'stat-featured':'')}><span>{label}</span><strong>{n}</strong></article>)}</section><section className="panel" style={{padding:24}}><h2>Inscrições recentes</h2>{!office.entries.length?<p>Ainda não foram recebidas inscrições. Pode registar um aluno no atendimento ou usar a pré-inscrição pública.</p>:office.entries.slice(-8).reverse().map(e=><div className="course-row" key={e.id}><div><strong>{office.students.find(s=>s.id===e.studentId)?.name}</strong><p>{office.courses.find(c=>c.id===e.courseId)?.name||e.requestedCourse} · {e.period}</p></div><span>{e.status}</span></div>)}<Button className="primary" onClick={()=>setPage('Inscrições')}>Abrir inscrições <ArrowRight size={18}/></Button></section></>}
</fieldset><footer className="workspace-footer"><span>© 2026 BEZA INOVAÇÕES · Construção & Formação</span><span>Centro de formação</span></footer></main></SidebarInset></SidebarProvider>;
}
