'use client';

import {sendRegistration,rpc} from '@/lib/supabase';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {flushSync} from 'react-dom';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,UserRound,BookOpen,Files,ClipboardCheck,Camera,Upload,FileText,Image as ImageIcon,Trash2,Eye,X,ShieldCheck,Phone,MessageCircle,Copy,RotateCcw,Info,LoaderCircle,GraduationCap,Pencil} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem,SelectGroup,SelectLabel} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {courseGroups,periods,genders,emptyRegistration,validatePersonal,validateCourse,validateDocuments,validateFile,todayISO,formatDate,displayCourse,type Registration,type Documents,type DocumentKind,type Errors} from '@/lib/registration';

const steps=[{title:'Dados pessoais',text:'Vamos conhecer-te',icon:UserRound},{title:'Curso pretendido',text:'Escolhe o teu caminho',icon:BookOpen},{title:'Documentos',text:'Prepara os anexos',icon:Files},{title:'Revisão e envio',text:'Confere os detalhes',icon:ClipboardCheck}];
const docLabels:Record<DocumentKind,string>={photo:'Fotografia do formando',identity:'BI ou Passaporte',payment:'Comprovativo de pagamento'};
const blankDocuments:Documents={photo:null,identity:null,payment:null};

function Field({id,label,error,hint,wide=false,children}:{id:string;label:string;error?:string;hint?:string;wide?:boolean;children:ReactNode}){return <div className={'reg-field '+(wide?'reg-wide':'')}><label htmlFor={id}>{label}<span aria-hidden="true"> *</span></label>{children}{hint&&<p className="reg-hint" id={id+'-hint'}>{hint}</p>}{error&&<p className="reg-error" id={id+'-error'}>{error}</p>}</div>;}
function useFileURL(file:File|null){const [url,setURL]=useState('');useEffect(()=>{if(!file){setURL('');return;}const next=URL.createObjectURL(file);setURL(next);return()=>URL.revokeObjectURL(next);},[file]);return url;}
function FilePreview({file,label}:{file:File;label:string}){const url=useFileURL(file);return file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')?<iframe src={url} title={label} sandbox="" className="reg-pdf"/>:<img className="reg-preview-image" src={url||undefined} alt={label}/>;}
function DocumentTile({kind,file,error,checking,onChoose,onRemove,onPreview,onCamera}:{kind:DocumentKind;file:File|null;error?:string;checking:boolean;onChoose:(file:File)=>void;onRemove:()=>void;onPreview:()=>void;onCamera:()=>void}){
 const input=useRef<HTMLInputElement>(null);const thumbnail=useFileURL(kind==='photo'?file:null);const [drag,setDrag]=useState(false);
 return <section className={'reg-document '+(error?'has-error':'')+(drag?' dragging':'')} aria-label={docLabels[kind]} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files[0])onChoose(e.dataTransfer.files[0]);}}>
  <div className="reg-doc-heading"><span className="reg-doc-icon">{kind==='photo'?<ImageIcon/>:<FileText/>}</span><div><h3>{docLabels[kind]}</h3><span>Obrigatório · {kind==='photo'?'JPG ou PNG':'JPG, PNG ou PDF'} · até 5 MB</span></div>{file&&!checking&&<CheckCircle2 className="reg-file-check" size={22}/>}</div>
  <input ref={input} id={kind} className="sr-only" type="file" accept={kind==='photo'?'.jpg,.jpeg,.png':'.jpg,.jpeg,.png,.pdf'} aria-label={'Selecionar '+docLabels[kind]} aria-invalid={!!error} aria-describedby={error?kind+'-error':undefined} onChange={e=>{const f=e.target.files?.[0];if(f)onChoose(f);e.target.value='';}}/>
  {checking?<div className="reg-file-state" role="status"><LoaderCircle className="reg-spin"/>A verificar o ficheiro…</div>:file?<div className="reg-file-state">{thumbnail?<img src={thumbnail} alt="Fotografia selecionada"/>:<FileText size={26}/>}<div><strong>{file.name}</strong><small>{(file.size/1024/1024).toFixed(2)} MB · selecionado neste dispositivo</small></div></div>:<p className="reg-doc-help">{kind==='photo'?'Escolhe uma fotografia nítida do rosto ou tira uma foto com a câmara.':kind==='identity'?'Anexa uma cópia legível do teu documento de identificação.':'Anexa o comprovativo da taxa de inscrição. O envio não confirma automaticamente a matrícula.'}</p>}
  <div className="reg-doc-actions"><Button type="button" variant="outline" onClick={()=>input.current?.click()}><Upload size={16}/>{file?'Substituir':'Escolher ficheiro'}</Button>{kind==='photo'&&<Button type="button" variant="ghost" onClick={onCamera}><Camera size={16}/>Usar câmara</Button>}{file&&<><Button type="button" variant="ghost" onClick={onPreview} aria-label={'Ver '+docLabels[kind]}><Eye size={17}/>Ver</Button><Button type="button" variant="ghost" onClick={onRemove} aria-label={'Remover '+docLabels[kind]}><Trash2 size={17}/></Button></>}</div>
  {error&&<p className="reg-error" id={kind+'-error'}>{error}</p>}
 </section>;
}
function CameraCapture({open,onClose,onCapture}:{open:boolean;onClose:()=>void;onCapture:(file:File)=>void}){
 const video=useRef<HTMLVideoElement>(null);const active=useRef<MediaStream|null>(null);const [error,setError]=useState('');const [ready,setReady]=useState(false);const [capturing,setCapturing]=useState(false);
 useEffect(()=>{if(!open)return;let cancelled=false;setReady(false);setError('');setCapturing(false);
  async function start(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280}},audio:false});if(cancelled){stream.getTracks().forEach(t=>t.stop());return;}active.current=stream;if(video.current){video.current.srcObject=stream;await video.current.play();}}catch(err){if(cancelled)return;active.current?.getTracks().forEach(t=>t.stop());active.current=null;const name=(err as Error).name;setError(name==='NotAllowedError'?'O acesso à câmara não foi autorizado. Podes escolher uma fotografia guardada no dispositivo.':name==='NotFoundError'?'Não foi encontrada uma câmara. Escolhe uma fotografia guardada no dispositivo.':'Não foi possível abrir a câmara. Fecha outras aplicações que a estejam a utilizar ou escolhe um ficheiro.');}}
  void start();return()=>{cancelled=true;active.current?.getTracks().forEach(t=>t.stop());active.current=null;};
 },[open]);
 async function capture(){if(!video.current?.videoWidth||!ready)return;setCapturing(true);const canvas=document.createElement('canvas');const ratio=Math.min(1,1280/video.current.videoWidth);canvas.width=Math.round(video.current.videoWidth*ratio);canvas.height=Math.round(video.current.videoHeight*ratio);const ctx=canvas.getContext('2d');if(!ctx){setError('Não foi possível captar a fotografia.');setCapturing(false);return;}ctx.drawImage(video.current,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(!active.current)return;if(blob){onCapture(new File([blob],'fotografia-formando.jpg',{type:'image/jpeg'}));onClose();}else{setError('Não foi possível captar a fotografia. Tenta novamente.');}setCapturing(false);},'image/jpeg',0.85);}
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="reg-dialog" showCloseButton={false}><DialogTitle>Fotografia do formando</DialogTitle><DialogDescription>Enquadra o rosto e confirma que existe boa iluminação. A fotografia será enviada com a inscrição.</DialogDescription><button className="reg-dialog-close" onClick={onClose} aria-label="Fechar câmara"><X size={20}/></button>{error?<p role="alert" className="reg-error-block">{error}</p>:<><video ref={video} autoPlay playsInline muted className="reg-camera" onLoadedData={()=>setReady(true)}/>{!ready&&<p role="status">A aguardar acesso à câmara…</p>}</>}<div className="reg-dialog-actions"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button className="primary" disabled={!ready||!!error||capturing} onClick={capture}><Camera size={18}/>{capturing?'A captar…':'Tirar fotografia'}</Button></div></DialogContent></Dialog>;
}

export default function RegistrationForm(){
 const [catalogReady,setCatalogReady]=useState(false);useEffect(()=>{rpc<{name:string;category:string}[]>('centro_catalog').then(list=>{const groups=new Map<string,string[]>();for(const c of list)groups.set(c.category,[...(groups.get(c.category)||[]),c.name]);courseGroups.splice(0,courseGroups.length,...Array.from(groups,([name,courses])=>({name,courses})));setCatalogReady(true);}).catch(()=>setErrors({review:'Não foi possível carregar os cursos. Atualize a página.'}));},[]);const [step,setStep]=useState(0);const [furthest,setFurthest]=useState(0);const [data,setData]=useState<Registration>({...emptyRegistration});const [files,setFiles]=useState<Documents>({...blankDocuments});const [errors,setErrors]=useState<Errors>({});const [checked,setChecked]=useState(false);const [checking,setChecking]=useState<Record<DocumentKind,boolean>>({photo:false,identity:false,payment:false});const [camera,setCamera]=useState(false);const [preview,setPreview]=useState<DocumentKind|null>(null);const [protocol,setProtocol]=useState('');const [sending,setSending]=useState(false);const requestId=useRef('');const [copied,setCopied]=useState('');const [leave,setLeave]=useState<'reset'|'dashboard'|null>(null);const [today,setToday]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);const errorSummary=useRef<HTMLDivElement>(null);const versions=useRef({photo:0,identity:0,payment:0});const submitted=useRef(false);const fileBusy=Object.values(checking).some(Boolean);const dirty=Object.entries(data).some(([k,v])=>k!=='documentType'&&v!=='')||Object.values(files).some(Boolean);
 const allowLeave=useRef(false);
 useEffect(()=>setToday(todayISO()),[]);
 useEffect(()=>{heading.current?.focus({preventScroll:true});},[step,protocol]);
 useEffect(()=>{if(Object.keys(errors).length)errorSummary.current?.focus({preventScroll:true});},[errors]);
 useEffect(()=>{if(!dirty||protocol)return;const before=(e:BeforeUnloadEvent)=>{if(allowLeave.current)return;e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty,protocol]);
 function update<K extends keyof Registration>(key:K,value:Registration[K]){setData(prev=>({...prev,[key]:value}));setErrors(prev=>({...prev,[key]:undefined}));setChecked(false);}
 function validations(index:number){return index===0?validatePersonal(data):index===1?validateCourse(data):validateDocuments(files);}
 function goTo(target:number){if(target<=step){setErrors({});setStep(target);return;}for(let i=0;i<target;i++){const e=validations(i);if(Object.keys(e).length){setStep(i);setErrors(e);return;}}setErrors({});setStep(target);setFurthest(prev=>Math.max(prev,target));window.scrollTo({top:0,behavior:'instant'});}
 async function choose(kind:DocumentKind,file:File){const version=++versions.current[kind];setFiles(prev=>({...prev,[kind]:null}));setChecking(prev=>({...prev,[kind]:true}));setChecked(false);setErrors(prev=>({...prev,[kind]:undefined}));try{let error=await validateFile(file,kind);if(!error&&!file.name.toLowerCase().endsWith('.pdf')){const bitmap=await createImageBitmap(file);bitmap.close();}if(version!==versions.current[kind])return;if(error)setErrors(prev=>({...prev,[kind]:error!}));else setFiles(prev=>({...prev,[kind]:file}));}catch{if(version===versions.current[kind])setErrors(prev=>({...prev,[kind]:'Não foi possível ler este ficheiro. Escolhe uma imagem ou documento válido.'}));}finally{if(version===versions.current[kind])setChecking(prev=>({...prev,[kind]:false}));}}
 function remove(kind:DocumentKind){versions.current[kind]++;setFiles(prev=>({...prev,[kind]:null}));setChecking(prev=>({...prev,[kind]:false}));setErrors(prev=>({...prev,[kind]:undefined}));setChecked(false);}
 async function submit(){if(submitted.current||fileBusy||sending||!catalogReady)return;if(step<3){goTo(step+1);return;}for(let i=0;i<3;i++){const e=validations(i);if(Object.keys(e).length){setStep(i);setErrors(e);return;}}if(!checked){setErrors({review:'Confirma que reviste os dados para enviar a pré-inscrição.'});return;}submitted.current=true;setErrors({});setSending(true);try{requestId.current ||= crypto.randomUUID();setProtocol(await sendRegistration(data,files,requestId.current));}catch(e){setErrors({review:(e as Error).message});submitted.current=false;}finally{setSending(false);}window.scrollTo({top:0,behavior:'instant'});}
 function reset(){requestId.current='';versions.current={photo:versions.current.photo+1,identity:versions.current.identity+1,payment:versions.current.payment+1};setData({...emptyRegistration});setFiles({...blankDocuments});setErrors({});setChecking({photo:false,identity:false,payment:false});setChecked(false);setProtocol('');setCopied('');setStep(0);setFurthest(0);submitted.current=false;setLeave(null);window.scrollTo({top:0,behavior:'instant'});}
 function leaveForDashboard(){if(dirty&&!protocol)setLeave('dashboard');else window.location.assign('/');}
 function fieldProps(key:keyof Registration){return {id:key,value:data[key],'aria-invalid':!!errors[key],'aria-describedby':errors[key]?key+'-error':undefined,onChange:(e:{target:{value:string}})=>update(key,e.target.value)};}
 function pick(key:keyof Registration,values:string[],placeholder:string){return <Select value={data[key]||null} onValueChange={v=>{if(v)update(key,v);}}><SelectTrigger id={key} aria-invalid={!!errors[key]} aria-describedby={errors[key]?key+'-error':undefined}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>;}
 async function copyProtocol(){try{await navigator.clipboard.writeText(protocol);setCopied('Protocolo copiado.');}catch{setCopied('Não foi possível copiar automaticamente. Seleciona e copia o protocolo apresentado.');}}
 const agentNavigate=useRef<(target:number)=>object>(()=>({}));
 agentNavigate.current=(target)=>{if(protocol||fileBusy)return {ok:false,reason:protocol?'Pré-inscrição já enviada.':'A verificar documentos.'};for(let i=0;i<target;i++){const e=validations(i);if(Object.keys(e).length){flushSync(()=>{setStep(i);setErrors(e);});return {ok:false,step:i+1,missingFields:Object.keys(e)};}}flushSync(()=>{setErrors({});setStep(target);setFurthest(prev=>Math.max(prev,target));});return {ok:true,step:target+1};};
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'navigate_registration_step',title:'Navegar na pré-inscrição',description:'Abre um passo do formulário de pré-inscrição. Valida os passos anteriores antes de avançar. Não envia dados nem cria inscrições.',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:1,maximum:4}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length!==1||!('step' in input)||!Number.isInteger(input.step)||Number(input.step)<1||Number(input.step)>4)throw new Error('Indica um passo inteiro entre 1 e 4.');return agentNavigate.current(Number(input.step)-1);}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Browsers without the proposed API keep the regular interface. */}
  return()=>lifecycle.abort();
 },[]);
 return <div className="reg-page"><header className="reg-header"><button className="reg-brand-button" onClick={leaveForDashboard} aria-label="BEZA Inovações — voltar ao painel"><div className="brand"><div className="brand-logo"><img src="/beza-reference.png" alt=""/></div><div><strong>BEZA<span> INOVAÇÕES</span></strong><small>CONSTRUÇÃO & FORMAÇÃO</small></div></div></button><div className="reg-header-links"><a href="tel:947968650"><Phone size={16}/><span>947 968 650</span></a><Button variant="outline" onClick={leaveForDashboard}>Voltar ao painel<ArrowRight size={16}/></Button></div></header>
 <div className="reg-demo"><Info size={17}/><span><strong>Pré-inscrição à distância.</strong> Anexe o comprovativo de pagamento da inscrição. A Secretaria analisará os dados e documentos antes de confirmar a matrícula.</span></div>
 <main className="reg-layout"><aside className="reg-sidebar"><span className="reg-kicker">PRÉ-INSCRIÇÃO ONLINE</span><h1>O teu próximo<br/>passo começa aqui.</h1><p>Escolhe a tua formação e prepara a inscrição, ao teu ritmo.</p><nav aria-label="Passos da pré-inscrição"><ol className="reg-steps">{steps.map((s,i)=><li key={s.title} className={i===step&&!protocol?'current':i<step||protocol?'complete':''}><button onClick={()=>goTo(i)} disabled={!!protocol||i>furthest||fileBusy} aria-current={i===step&&!protocol?'step':undefined}><span className="reg-step-number">{i<step||protocol?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><span><strong>{s.title}</strong><small>{s.text}</small></span></button></li>)}</ol></nav><div className="reg-help"><MessageCircle size={23}/><h2>Estamos aqui para ajudar.</h2><p>Dúvidas sobre a formação ou os documentos necessários?</p><a href="https://wa.me/351920244269" target="_blank" rel="noreferrer">Falar com o centro<ArrowRight size={16}/></a><small>WhatsApp: +351 920 244 269</small></div><div className="reg-side-footer"><GraduationCap size={20}/><span>25 cursos · 4 áreas de formação</span></div></aside>
 <div className="reg-main-column">{protocol?<section className="reg-form-card reg-success" aria-labelledby="step-heading"><div className="reg-success-icon"><CheckCircle2 size={42}/></div><span className="reg-kicker">PRÉ-INSCRIÇÃO RECEBIDA</span><h2 ref={heading} tabIndex={-1} id="step-heading">A tua pré-inscrição foi recebida.</h2><p>Os dados e documentos foram guardados. A Secretaria ou o Administrador irá analisar a tua inscrição.</p><span className="reg-pending">Pendente de confirmação · pré-inscrição</span><div className="reg-protocol"><span>PROTOCOLO DE PRÉ-INSCRIÇÃO</span><strong>{protocol}</strong><Button variant="outline" onClick={copyProtocol}><Copy size={16}/>Copiar protocolo</Button>{copied&&<small role="status">{copied}</small>}</div><dl className="reg-success-details"><div><dt>Formando</dt><dd>{data.name}</dd></div><div><dt>Curso pretendido</dt><dd>{displayCourse(data)}</dd></div><div><dt>Período e início pretendido</dt><dd>{data.period} · {formatDate(data.startDate)}</dd></div></dl><div className="reg-next-info"><h3>O que acontece a seguir?</h3><ol><li>A secretaria verificará os dados e os documentos.</li><li>Após confirmação manual, será atribuída a matrícula.</li><li>Contacta o centro com este protocolo para confirmar a data de arranque do curso.</li></ol><p>Este protocolo não é uma matrícula nem um comprovativo oficial.</p></div><div className="reg-success-actions"><Button className="primary" onClick={()=>setLeave('reset')}><RotateCcw size={17}/>Nova pré-inscrição</Button><Button variant="outline" onClick={leaveForDashboard}>Voltar ao painel</Button></div></section>:<form className="reg-form-card" noValidate onSubmit={e=>{e.preventDefault();submit();}}><div className="reg-form-heading"><div className="reg-heading-line"><span className="reg-kicker">PASSO {step+1} DE 4</span><span className="reg-save-note">Sem necessidade de criar conta</span></div><Progress value={(step+1)*25} aria-label={`Passo ${step+1} de 4`} className="reg-progress"/><h2 ref={heading} tabIndex={-1} id="step-heading">{steps[step].title}</h2><p>{['Preenche os dados do formando, tal como aparecem no documento de identificação.','Encontra o curso que procuras e indica quando gostarias de começar.','Adiciona os três documentos necessários para a análise da secretaria.','Confere os dados e os anexos antes de enviar a pré-inscrição.'][step]}</p>{step<3&&<small>Os campos assinalados com * são obrigatórios.</small>}</div>
 {Object.values(errors).some(Boolean)&&<div className="reg-error-block" ref={errorSummary} tabIndex={-1} role="alert"><strong>Revê os campos indicados abaixo.</strong><ul>{Object.entries(errors).filter(([,v])=>!!v).map(([k,v])=><li key={k}>{v}</li>)}</ul></div>}
 {step===0&&<div className="reg-fields"><Field id="name" label="Nome completo" error={errors.name} wide><Input {...fieldProps('name')} placeholder="Ex.: Ana Manuel Francisco" maxLength={150} autoComplete="off" required/></Field><Field id="birthDate" label="Data de nascimento" error={errors.birthDate}><Input {...fieldProps('birthDate')} type="date" max={today||undefined} required/></Field><Field id="gender" label="Género" error={errors.gender}>{pick('gender',genders,'Seleciona uma opção')}</Field><Field id="nationality" label="Nacionalidade" error={errors.nationality}><Input {...fieldProps('nationality')} placeholder="Ex.: Angolana" maxLength={80} required/></Field><Field id="documentType" label="Documento de identificação" error={errors.documentType}>{pick('documentType',['BI','Passaporte'],'Seleciona o documento')}</Field><Field id="documentNumber" label={'Número do '+data.documentType} error={errors.documentNumber}><Input {...fieldProps('documentNumber')} placeholder={data.documentType==='BI'?'Ex.: 000000000LA000':'Número do passaporte'} maxLength={35} autoComplete="off" required/></Field><Field id="phone" label="Telefone / WhatsApp" error={errors.phone} hint="Para números fora de Angola, inclui o indicativo do país."><Input {...fieldProps('phone')} type="tel" placeholder="Ex.: +244 9XX XXX XXX" maxLength={25} autoComplete="off" required/></Field><Field id="address" label="Morada atual" error={errors.address} wide><Textarea {...fieldProps('address')} placeholder="Província, município, bairro e rua" maxLength={250} rows={3} autoComplete="off" required/></Field></div>}
 {step===1&&<div className="reg-fields"><Field id="course" label="Curso pretendido" error={errors.course} wide><Select value={data.course||null} onValueChange={v=>{if(v)update('course',v);}}><SelectTrigger id="course" aria-invalid={!!errors.course} aria-describedby={errors.course?'course-error':undefined}><SelectValue placeholder="Seleciona um dos 25 cursos"/></SelectTrigger><SelectContent className="reg-course-menu">{courseGroups.map(group=><SelectGroup key={group.name}><SelectLabel>{group.name}</SelectLabel>{group.courses.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectGroup>)}<SelectItem value="Outro">Outro — não encontrei o curso pretendido</SelectItem></SelectContent></Select></Field>{data.course==='Outro'&&<Field id="otherCourse" label="Qual é o curso pretendido?" error={errors.otherCourse} hint="A secretaria avaliará o pedido e entrará em contacto no sistema final." wide><Input {...fieldProps('otherCourse')} placeholder="Escreve o nome da formação" maxLength={150} required/></Field>}{data.course&&<div className="reg-course-summary reg-wide"><div><BookOpen size={24}/><span>{courseGroups.find(g=>g.courses.includes(data.course))?.name||'Pedido de formação'}<strong>{displayCourse(data)||'Curso a indicar'}</strong></span></div><dl><div><dt>Duração</dt><dd>Por definir</dd></div><div><dt>Carga horária</dt><dd>Por definir</dd></div><div><dt>Preço (AOA)</dt><dd>Por definir</dd></div></dl></div>}<Field id="period" label="Período preferido" error={errors.period}>{pick('period',periods,'Seleciona o período')}</Field><Field id="startDate" label="Data prevista de início" error={errors.startDate}><Input {...fieldProps('startDate')} type="date" min={today||undefined} required/></Field><div className="reg-info-box reg-wide"><Info size={20}/><p>O período e a data são preferências. A secretaria confirmará a disponibilidade e o início da turma. A pré-inscrição ainda não garante uma matrícula.</p></div></div>}
 {step===2&&<div className="reg-documents">{(['photo','identity','payment'] as DocumentKind[]).map(kind=><DocumentTile key={kind} kind={kind} file={files[kind]} error={errors[kind]} checking={checking[kind]} onChoose={file=>void choose(kind,file)} onRemove={()=>remove(kind)} onPreview={()=>setPreview(kind)} onCamera={()=>setCamera(true)}/>)}<div className="reg-info-box"><ShieldCheck size={21}/><p>Os anexos ficam apenas na memória desta página. Se fechares ou atualizares a página, terás de os selecionar novamente. Nesta prévia, não uses documentos reais.</p></div></div>}
 {step===3&&<div className="reg-review"><ReviewSection title="Dados pessoais" edit={()=>goTo(0)}><dl className="reg-review-grid">{[['Nome completo',data.name],['Data de nascimento',formatDate(data.birthDate)],['Género',data.gender],['Nacionalidade',data.nationality],[data.documentType,data.documentNumber],['Telefone / WhatsApp',data.phone],['Morada atual',data.address]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></ReviewSection><ReviewSection title="Curso pretendido" edit={()=>goTo(1)}><dl className="reg-review-grid"><div className="reg-wide"><dt>Curso</dt><dd>{displayCourse(data)}</dd></div><div><dt>Período</dt><dd>{data.period}</dd></div><div><dt>Data prevista</dt><dd>{formatDate(data.startDate)}</dd></div><div className="reg-wide"><dt>Preço, duração e carga horária</dt><dd>Por definir pelo centro</dd></div></dl></ReviewSection><ReviewSection title="Documentos selecionados" edit={()=>goTo(2)}>{(['photo','identity','payment'] as DocumentKind[]).map(kind=><div className="reg-review-file" key={kind}><CheckCircle2 size={19}/><div><strong>{docLabels[kind]}</strong><small>{files[kind]?.name}</small></div><Button type="button" variant="ghost" onClick={()=>setPreview(kind)} aria-label={'Ver '+docLabels[kind]}><Eye size={18}/>Ver</Button></div>)}</ReviewSection><div className="reg-confirm-check"><Checkbox id="review" checked={checked} onCheckedChange={v=>{setChecked(v);setErrors(prev=>({...prev,review:undefined}));}} aria-invalid={!!errors.review} aria-describedby={errors.review?'review-error':undefined}/><label htmlFor="review">Revi os dados e autorizo o envio dos documentos para análise da minha inscrição.</label></div>{errors.review&&<p id="review-error" className="reg-error">{errors.review}</p>}<div className="reg-info-box"><Info size={20}/><p>A matrícula só será emitida depois da aprovação pela Secretaria ou pelo Administrador. Guarde o protocolo para acompanhar o pedido.</p></div></div>}
 <div className="reg-form-actions"><Button type="button" variant="ghost" onClick={()=>step?goTo(step-1):leaveForDashboard()}><ArrowLeft size={17}/>{step?'Voltar':'Sair'}</Button><Button type="submit" className="primary" disabled={fileBusy||sending}>{step===3?'Simular envio':step===2?'Rever pré-inscrição':'Continuar'}<ArrowRight size={18}/></Button></div></form>}
 <footer className="reg-footer"><span>© 2026 BEZA INOVAÇÕES · Construção & Formação</span><div><a href="tel:947968650">947 968 650</a><span>/</span><a href="tel:952042462">952 042 462</a></div></footer></div></main>
 <CameraCapture open={camera} onClose={()=>setCamera(false)} onCapture={file=>void choose('photo',file)}/>
 <Dialog open={!!preview} onOpenChange={v=>{if(!v)setPreview(null);}}><DialogContent className="reg-dialog reg-file-dialog" showCloseButton={false}><DialogTitle>{preview?docLabels[preview]:''}</DialogTitle><DialogDescription>Pré-visualização local do ficheiro selecionado.</DialogDescription><button className="reg-dialog-close" onClick={()=>setPreview(null)} aria-label="Fechar pré-visualização"><X size={20}/></button>{preview&&files[preview]&&<FilePreview file={files[preview]!} label={docLabels[preview]}/>}<Button variant="outline" onClick={()=>setPreview(null)}>Fechar</Button></DialogContent></Dialog>
 <AlertDialog open={!!leave} onOpenChange={v=>{if(!v)setLeave(null);}}><AlertDialogContent><AlertDialogTitle>{leave==='reset'?'Iniciar uma nova pré-inscrição?':'Sair da pré-inscrição?'}</AlertDialogTitle><AlertDialogDescription>Os dados e os documentos desta pré-inscrição serão descartados. Não foram guardados no centro.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel onClick={()=>setLeave(null)}>Continuar aqui</AlertDialogCancel><AlertDialogAction onClick={()=>{if(leave==='reset')reset();else{allowLeave.current=true;setLeave(null);window.location.assign('/');}}}>{leave==='reset'?'Nova pré-inscrição':'Sair'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function ReviewSection({title,edit,children}:{title:string;edit:()=>void;children:ReactNode}){return <section className="reg-review-section"><div className="reg-review-heading"><h3>{title}</h3><Button type="button" variant="ghost" onClick={edit}><Pencil size={15}/>Editar</Button></div>{children}</section>;}

