import type {Office,Entry} from './office';
export const trainers=[{id:'f1',name:'Cláudia Santos'},{id:'f2',name:'António Paulo'}];
export const weekdays=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];
export type Cohort={id:string;name:string;courseId:string;period:string;start:string;end:string;days:number[];from:string;to:string;room:string;trainerId:string};
export type Session={cohortId:string;date:string;marks:Record<string,'Presente'|'Falta'>};
export type Assessment={id:string;cohortId:string;name:string;date:string;scores:Record<string,number>};
export type Academic={cohorts:Cohort[];assignments:Record<string,string>;sessions:Session[];assessments:Assessment[]};
export function initialAcademic():Academic{return {cohorts:[{id:'t1',name:'Informática · Setembro A',courseId:'c1-1',period:'Manhã',start:'2026-09-07',end:'2026-11-30',days:[1,2,4],from:'09:00',to:'11:00',room:'Sala 02',trainerId:'f1'},{id:'t2',name:'Eletricidade · Setembro A',courseId:'c3-7',period:'Tarde',start:'2026-09-07',end:'2026-11-30',days:[2,4],from:'14:00',to:'16:00',room:'Oficina 01',trainerId:'f2'}],assignments:{'PRE-DEMO-004':'t1','PRE-DEMO-002':'t2'},sessions:[{cohortId:'t1',date:'2026-09-08',marks:{'PRE-DEMO-004':'Presente'}},{cohortId:'t2',date:'2026-09-08',marks:{'PRE-DEMO-002':'Falta'}}],assessments:[{id:'a1',cohortId:'t1',name:'Diagnóstico inicial',date:'2026-09-08',scores:{'PRE-DEMO-004':16}}]};}
export const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
export function cohortErrors(c:Cohort,state:Academic,office:Office){const e:Record<string,string>={};if(c.name.trim().length<3||c.name.length>100)e.name='Indica um nome entre 3 e 100 caracteres.';if(!office.courses.some(x=>x.id===c.courseId&&x.active))e.courseId='Seleciona um curso ativo.';if(!['Manhã','Tarde','Noite','Fim de semana'].includes(c.period))e.period='Seleciona o período.';if(!trainers.some(t=>t.id===c.trainerId))e.trainerId='Seleciona o formador.';if(!validDate(c.start)||!validDate(c.end)||c.end<c.start)e.start='Indica datas válidas; o fim não pode ser anterior ao início.';if(!c.days.length||c.days.some(d=>!Number.isInteger(d)||d<0||d>6))e.days='Seleciona pelo menos um dia da semana.';if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(c.from)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(c.to)||c.from>=c.to)e.from='O horário de fim deve ser posterior ao início.';if(c.room.trim().length<2||c.room.length>80)e.room='Indica a sala ou local (2 a 80 caracteres).';if(state.cohorts.some(t=>t.id!==c.id&&t.name.trim().toLowerCase()===c.name.trim().toLowerCase()))e.name='Já existe uma turma com este nome.';if(state.cohorts.some(t=>t.id!==c.id&&t.start<=c.end&&t.end>=c.start&&t.days.some(d=>c.days.includes(d))&&t.from<c.to&&t.to>c.from&&(t.trainerId===c.trainerId||t.room.trim().toLowerCase()===c.room.trim().toLowerCase())))e.from='Há sobreposição de horários para este formador ou sala.';return e;}
export function roster(state:Academic,office:Office,cohortId:string){return office.entries.filter(e=>e.status==='Confirmada'&&state.assignments[e.id]===cohortId);}
export function assignEntry(state:Academic,office:Office,entryId:string,cohortId:string):Academic{const e=office.entries.find(e=>e.id===entryId),c=state.cohorts.find(c=>c.id===cohortId);if(!e||!c||e.status!=='Confirmada'||e.courseId!==c.courseId||e.period!==c.period)throw new Error('Só é possível associar inscrições confirmadas do mesmo curso e período.');if(state.assignments[entryId])throw new Error('Esta inscrição já está associada a uma turma.');return {...state,assignments:{...state.assignments,[entryId]:cohortId}};}
export function assertTeacher(state:Academic,cohortId:string,trainerId:string){if(!state.cohorts.some(c=>c.id===cohortId&&c.trainerId===trainerId))throw new Error('Esta turma não está atribuída ao formador selecionado.');}
function checkDate(c:Cohort,date:string,today:string){if(!validDate(date)||date<c.start||date>c.end||date>today)throw new Error('Escolhe uma data dentro do período da turma, até hoje.');}
export function saveSession(state:Academic,office:Office,session:Session,trainerId:string,today:string):Academic{assertTeacher(state,session.cohortId,trainerId);const c=state.cohorts.find(c=>c.id===session.cohortId)!;checkDate(c,session.date,today);if(!c.days.includes(new Date(session.date+'T12:00:00Z').getUTCDay()))throw new Error('A data escolhida não corresponde a um dia de aula desta turma.');const ids=roster(state,office,c.id).map(e=>e.id);if(!ids.length)throw new Error('A turma ainda não tem alunos.');if(Object.keys(session.marks).some(id=>!ids.includes(id))||ids.some(id=>!['Presente','Falta'].includes(session.marks[id])))throw new Error('Marca a presença ou falta de todos os alunos antes de guardar.');return {...state,sessions:[...state.sessions.filter(s=>s.cohortId!==c.id||s.date!==session.date),{...session,marks:{...session.marks}}]};}
export function saveAssessment(state:Academic,office:Office,a:Assessment,trainerId:string,today:string):Academic{assertTeacher(state,a.cohortId,trainerId);const c=state.cohorts.find(c=>c.id===a.cohortId)!;checkDate(c,a.date,today);if(a.name.trim().length<3||a.name.length>100)throw new Error('Indica o nome da avaliação (3 a 100 caracteres).');if(state.assessments.some(x=>x.id!==a.id&&x.cohortId===a.cohortId&&x.name.trim().toLowerCase()===a.name.trim().toLowerCase()))throw new Error('Já existe uma avaliação com este nome nesta turma.');const ids=roster(state,office,c.id).map(e=>e.id);if(!Object.keys(a.scores).length)throw new Error('Indica pelo menos uma nota.');if(Object.entries(a.scores).some(([id,n])=>!ids.includes(id)||!Number.isFinite(n)||n<0||n>20))throw new Error('As notas devem estar entre 0 e 20 e pertencer a alunos desta turma.');return {...state,assessments:[...state.assessments.filter(x=>x.id!==a.id),{...a,name:a.name.trim(),scores:{...a.scores}}]};}
export function progress(state:Academic,entry:Entry){const sessions=state.sessions.filter(s=>s.cohortId===state.assignments[entry.id]&&s.marks[entry.id]);const present=sessions.filter(s=>s.marks[entry.id]==='Presente').length;const scores=state.assessments.filter(a=>a.cohortId===state.assignments[entry.id]&&a.scores[entry.id]!==undefined).map(a=>a.scores[entry.id]);return {sessions:sessions.length,present,percent:sessions.length?Math.round(present/sessions.length*100):null,average:scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null};}
