import {PDFDocument,StandardFonts,rgb,pushGraphicsState,popGraphicsState,rectangle,clip,endPath,type PDFFont} from 'pdf-lib';
import QRCode from 'qrcode';
export type DocumentData={official?:boolean;verificationToken?:string;kind:'Inscrição'|'Pagamento'|'Certificado';reference:string;name:string;course:string;issued:string;rows:[string,string][];statement:string};
export const verificationOrigin='https://beza-inovacoes-centro.wbmsmarttech.chatgpt.site';
export function verificationURL(reference:string){return verificationOrigin+'/verificar?ref='+encodeURIComponent(reference);}
function printable(text:string,font:PDFFont){return Array.from(text.replace(/[\r\n\t]/g,' ')).map(c=>{try{font.encodeText(c);return c;}catch{return '?';}}).join('');}
function wrap(text:string,font:PDFFont,size:number,width:number){const lines:string[]=[];let line='';for(const c of printable(text,font)){if(font.widthOfTextAtSize(line+c,size)>width){const space=line.lastIndexOf(' ');if(space>line.length/2){lines.push(line.slice(0,space));line=line.slice(space+1)+c;}else{lines.push(line);line=c;}}else line+=c;}if(line)lines.push(line.trim());return lines;}
export async function createDocument(data:DocumentData,logoBytes?:Uint8Array){const pdf=await PDFDocument.create();pdf.setTitle(`BEZA - ${data.kind}${data.official?'':' - DEMONSTRAÇÃO'}`);pdf.setAuthor('BEZA INOVAÇÕES');pdf.setSubject(data.official?'Comprovativo de inscrição confirmada':'Documento demonstrativo sem validade oficial');const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const orange=rgb(.95,.42,.13),dark=rgb(.1,.12,.14),gray=rgb(.38,.42,.46);const logo=logoBytes?await pdf.embedPng(logoBytes):null;const qr=QRCode.create(verificationURL(data.verificationToken||data.reference),{errorCorrectionLevel:'M'}).modules;
 let page=pdf.addPage([595.28,841.89]),y=680;
 function decorate(){page.drawRectangle({x:0,y:729,width:595.28,height:113,color:dark});page.drawRectangle({x:0,y:724,width:595.28,height:5,color:orange});page.drawText('BEZA INOVAÇÕES',{x:125,y:789,size:24,font:bold,color:rgb(1,1,1)});page.drawText('CONSTRUÇÃO & FORMAÇÃO',{x:126,y:766,size:11,font,color:rgb(.82,.85,.87)});if(logo){page.pushOperators(pushGraphicsState(),rectangle(43,766,65,49),clip(),endPath());page.drawImage(logo,{x:43-94,y:751+64+12-255*700/902,width:255,height:255*700/902});page.pushOperators(popGraphicsState());}page.drawRectangle({x:42,y:686,width:511,height:25,color:rgb(1,.94,.88)});page.drawText(data.official?'INSCRIÇÃO CONFIRMADA':'DEMONSTRAÇÃO - SEM VALIDADE OFICIAL',{x:55,y:694,size:12,font:bold,color:rgb(.61,.24,.06)});
 const unit=94/(qr.size+8);page.drawRectangle({x:447,y:53,width:94,height:94,color:rgb(1,1,1)});for(let r=0;r<qr.size;r++)for(let c=0;c<qr.size;c++)if(qr.get(r,c))page.drawRectangle({x:447+(c+4)*unit,y:53+(qr.size+3-r)*unit,width:unit,height:unit,color:dark});page.drawText(data.official?'Verificar inscrição':'QR de demonstração',{x:443,y:38,size:9,font,color:gray});page.drawLine({start:{x:42,y:164},end:{x:553,y:164},thickness:1,color:rgb(.85,.87,.89)});page.drawText('REFERÊNCIA',{x:43,y:141,size:9,font:bold,color:gray});page.drawText(printable(data.reference,font),{x:43,y:125,size:11,font:bold,color:dark});page.drawText(data.official?'Apresentar à Secretaria para assinatura e carimbo.':'Sem assinatura ou carimbo válidos. Não comprova matrícula,',{x:43,y:98,size:10,font,color:gray});page.drawText(data.official?'Não certifica a conclusão da formação.':'pagamento, conclusão ou autenticidade de uma formação.',{x:43,y:82,size:10,font,color:gray});page.drawText('Contactos: 947 968 650 / 952 042 462',{x:43,y:55,size:10,font,color:gray});}
 decorate();y=649;
 function text(value:string,size=12,strong=false){const f=strong?bold:font;for(const line of wrap(value,f,size,505)){if(y<215){page=pdf.addPage([595.28,841.89]);decorate();y=650;}page.drawText(line,{x:44,y,size,font:f,color:strong?dark:gray});y-=size+6;}y-=8;}
 text(data.kind==='Inscrição'?'Comprovativo de inscrição':data.kind==='Pagamento'?'Comprovativo de pagamento':'Certificado de formação',25,true);
 text(data.name,19,true);text(data.course,15,true);text(data.statement,12);y-=6;
 for(const [label,value] of [['Data de emissão',data.issued],...data.rows]){text(label.toUpperCase(),9,true);text(value,12);}
 if(y<253){page=pdf.addPage([595.28,841.89]);decorate();} {page.drawLine({start:{x:44,y:221},end:{x:244,y:221},thickness:.7,color:gray});page.drawText(data.official?'Assinatura e carimbo da Secretaria':'Assinatura e carimbo - apenas modelo',{x:44,y:204,size:9,font,color:gray});}
 if(data.official&&data.verificationToken){page.drawText('Código: '+data.verificationToken,{x:43,y:24,size:8,font,color:gray});}
 return pdf.save();}
