import type {Office} from './office';
import type {Academic} from './academic';
import {progress,validDate} from './academic';
export type Charge={id:string;entryId:string;kind:'Inscrição'|'Propina';month:string;amount:number;due:string};
export type Payment={id:string;chargeId:string;amount:number;date:string;method:string;reference:string;actor:string;voidReason:string;voidActor?:string;voidAt?:string};
export type Certificate={id:string;entryId:string;issued:string;name:string;course:string;hours:string;duration:string;frequency:number;average:number;minFrequency:number;minGrade:number;actor:string};
export type Finance={charges:Charge[];payments:Payment[];certificates:Certificate[];minFrequency:number;minGrade:number};
export const methods=['Transferência bancária','Depósito bancário','Numerário','Multicaixa'];
export function initialFinance():Finance{return {charges:[{id:'COB-DEMO-001',entryId:'PRE-DEMO-004',kind:'Inscrição',month:'',amount:1500000,due:'2026-09-07'},{id:'COB-DEMO-002',entryId:'PRE-DEMO-004',kind:'Propina',month:'2026-09',amount:2500000,due:'2026-09-10'},{id:'COB-DEMO-003',entryId:'PRE-DEMO-002',kind:'Propina',month:'2026-09',amount:2500000,due:'2026-09-10'}],payments:[{id:'PAG-DEMO-001',chargeId:'COB-DEMO-001',amount:1500000,date:'2026-09-07',method:'Transferência bancária',reference:'EXEMPLO-001',actor:'Financeiro (exemplo)',voidReason:''},{id:'PAG-DEMO-002',chargeId:'COB-DEMO-002',amount:1000000,date:'2026-09-08',method:'Depósito bancário',reference:'EXEMPLO-002',actor:'Financeiro (exemplo)',voidReason:''}],certificates:[],minFrequency:75,minGrade:10};}
export function cents(input:string){if(!/^\d+(?:[.,]\d{1,2})?$/.test(input.trim()))throw new Error('Indica um valor válido, com até duas casas decimais.');const [whole,frac='']=input.trim().replace(',','.').split('.');const amount=Number(whole)*100+Number(frac.padEnd(2,'0'));if(!Number.isSafeInteger(amount)||amount<=0||amount>10000000000)throw new Error('O valor deve ser maior que zero e até 100 000 000 AOA.');return amount;}
export const formatMoney=(amount:number)=>new Intl.NumberFormat('pt-AO',{minimumFractionDigits:2,maximumFractionDigits:2}).format(amount/100)+' AOA';
export function paid(state:Finance,id:string){return state.payments.filter(p=>p.chargeId===id&&!p.voidReason).reduce((n,p)=>n+p.amount,0);}
export function balance(state:Finance,c:Charge){return c.amount-paid(state,c.id);}
export function chargeStatus(state:Finance,c:Charge,today:string){const b=balance(state,c);return b===0?'Liquidada':paid(state,c.id)>0?(c.due<today?'Parcial em atraso':'Parcial'):c.due<today?'Em atraso':'Por pagar';}
function assertFinance(role:string){if(!['Administrador','Financeiro'].includes(role))throw new Error('Esta operação está disponível ao Administrador e Financeiro.');}
export function addCharge(state:Finance,office:Office,c:Charge,role:string):Finance{assertFinance(role);if(!office.entries.some(e=>e.id===c.entryId&&e.status==='Confirmada'))throw new Error('Seleciona uma inscrição confirmada.');if(!Number.isSafeInteger(c.amount)||c.amount<=0||c.amount>10000000000)throw new Error('Valor inválido.');if(!validDate(c.due))throw new Error('Indica uma data de vencimento válida.');if(!['Inscrição','Propina'].includes(c.kind))throw new Error('Tipo de cobrança inválido.');if(c.kind==='Propina'&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(c.month))throw new Error('Seleciona o mês da propina.');if(state.charges.some(x=>x.entryId===c.entryId&&x.kind===c.kind&&(c.kind==='Inscrição'||x.month===c.month)))throw new Error('Já existe esta cobrança para a inscrição e período.');if(state.charges.some(x=>x.id===c.id))throw new Error('Cobrança já registada.');return {...state,charges:[...state.charges,{...c,month:c.kind==='Propina'?c.month:''}]};}
export function addPayment(state:Finance,p:Payment,role:string,today:string):Finance{assertFinance(role);const c=state.charges.find(c=>c.id===p.chargeId);if(!c)throw new Error('Seleciona uma cobrança existente.');if(!validDate(p.date)||p.date>today)throw new Error('Indica uma data válida, até hoje.');if(!Number.isSafeInteger(p.amount)||p.amount<=0||p.amount>balance(state,c))throw new Error('O pagamento deve ser positivo e não pode ultrapassar o saldo em falta.');if(!methods.includes(p.method))throw new Error('Seleciona o método de pagamento.');if(p.reference.trim().length<3||p.reference.length>100)throw new Error('Indica uma referência de 3 a 100 caracteres.');if(state.payments.some(x=>x.id===p.id||(!x.voidReason&&x.reference.trim().toLowerCase()===p.reference.trim().toLowerCase())))throw new Error('Já existe um pagamento com esta referência.');return {...state,payments:[...state.payments,{...p,actor:role,reference:p.reference.trim(),voidReason:''}]};}
export function voidPayment(state:Finance,id:string,reason:string,role:string):Finance{assertFinance(role);if(reason.trim().length<5||reason.length>500)throw new Error('Indica o motivo do estorno (5 a 500 caracteres).');const p=state.payments.find(x=>x.id===id);if(!p||p.voidReason)throw new Error('Este pagamento não está ativo.');return {...state,payments:state.payments.map(p=>p.id===id?{...p,voidReason:reason.trim(),voidActor:role,voidAt:new Date().toISOString()}:p)};}
export function eligibility(state:Finance,office:Office,academic:Academic,entryId:string){const entry=office.entries.find(e=>e.id===entryId),course=office.courses.find(c=>c.id===entry?.courseId),cohort=academic.cohorts.find(c=>c.id===academic.assignments[entryId]);const reasons:string[]=[];if(!entry||entry.status!=='Confirmada')reasons.push('A inscrição precisa de estar confirmada.');if(!cohort)reasons.push('Associa o aluno a uma turma.');if(!course?.duration||!course.hours||Number(course.hours)<=0)reasons.push('Define a duração e a carga horária no cadastro do curso.');const p=entry?progress(academic,entry):null;if(p?.percent===null||!p?.sessions)reasons.push('Regista presenças antes de emitir.');else if(p.present/p.sessions*100<state.minFrequency)reasons.push(`Frequência mínima: ${state.minFrequency}%.`);if(p?.average===null||p?.average===undefined)reasons.push('Regista pelo menos uma avaliação.');else if(p.average<state.minGrade)reasons.push(`Média mínima: ${state.minGrade}/20.`);return {reasons,progress:p,course,entry};}
export function issueCertificate(state:Finance,office:Office,academic:Academic,entryId:string,completed:boolean,role:string,today:string):Finance{if(!['Administrador','Secretaria'].includes(role))throw new Error('A emissão é feita pelo Administrador ou Secretaria.');if(!completed)throw new Error('Confirma a conclusão da formação nesta simulação.');if(state.certificates.some(c=>c.entryId===entryId))throw new Error('Já existe um certificado para esta inscrição.');const check=eligibility(state,office,academic,entryId);if(check.reasons.length)throw new Error(check.reasons.join(' '));const student=office.students.find(s=>s.id===check.entry!.studentId)!;return {...state,certificates:[...state.certificates,{id:'CERT-DEMO-'+entryId.replace('PRE-DEMO-',''),entryId,issued:today,name:student.name,course:check.course!.name,hours:check.course!.hours,duration:check.course!.duration,frequency:check.progress!.percent!,average:check.progress!.average!,minFrequency:state.minFrequency,minGrade:state.minGrade,actor:role}]};}
export function csvCell(value:unknown){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function toCSV(rows:unknown[][]){return '\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n');}
